import { INodeProperties } from 'n8n-workflow';

export const updateDescription: INodeProperties[] = [
	{
		displayName: 'Site ID',
		name: 'id',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['sites'],
				operation: ['update'],
			},
		},
		default: 0,
		required: true,
		description: 'The ID of the site to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['sites'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Accounts BCC Email Address',
				name: 'accountsbccemailaddress',
				type: 'string',
				default: '',
				description: 'BCC email address for accounts',
			},
			{
				displayName: 'Accounts CC Email Address',
				name: 'accountsccemailaddress',
				type: 'string',
				default: '',
				description: 'CC email address for accounts',
			},
			{
				displayName: 'Accounts Email Address',
				name: 'accountsemailaddress',
				type: 'string',
				default: '',
				description: 'Primary email address for accounts',
			},
			{
				displayName: 'Accounts First Name',
				name: 'accountsfirstname',
				type: 'string',
				default: '',
				description: 'First name of accounts contact',
			},
			{
				displayName: 'Accounts ID',
				name: 'accountsid',
				type: 'string',
				default: '',
				description: 'Accounts system ID',
			},
			{
				displayName: 'Accounts Last Name',
				name: 'accountslastname',
				type: 'string',
				default: '',
				description: 'Last name of accounts contact',
			},
			{
				displayName: 'Client Name or ID',
				name: 'client_id',
				type: 'options',
				typeOptions: {
					loadOptionsMethod: 'getClients',
				},
				default: '',
				description: 'The client that owns this site. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Colour',
				name: 'colour',
				type: 'color',
				default: '',
				description: 'Color code for the site',
			},
			{
				displayName: 'Default Delivery',
				name: 'defaultdelivery',
				type: 'boolean',
				default: false,
				description: 'Whether this is the default delivery site',
			},
			{
				displayName: 'Default Stock Location',
				name: 'defaultstocklocation',
				type: 'number',
				default: 0,
				description: 'Default stock location ID',
			},
			{
				displayName: 'Deliver By Name or ID',
				name: 'deliverby',
				type: 'options',
				typeOptions: {
					loadOptionsDependsOn: ['updateFields.client_id'],
					loadOptionsMethod: 'getClientUsers',
				},
				default: '',
				description: 'User for delivery contact. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Disclaimer Match String',
				name: 'disclaimermatchstring',
				type: 'string',
				default: '',
				description: 'String to match for disclaimer',
			},
			{
				displayName: 'Email Domain',
				name: 'emaildomain',
				type: 'string',
				default: '',
				description: 'Email domain for the site',
			},
			{
				displayName: 'Email Subject Prefix',
				name: 'emailsubjectprefix',
				type: 'string',
				default: '',
				description: 'Prefix to add to email subjects',
			},
			{
				displayName: 'Facilities Manager Name or ID',
				name: 'facilitiesmanager',
				type: 'options',
				typeOptions: {
					loadOptionsDependsOn: ['updateFields.client_id'],
					loadOptionsMethod: 'getClientUsers',
				},
				default: '',
				description: 'User for facilities manager. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Geocoord 1',
				name: 'geocoord1',
				type: 'number',
				default: 0,
				description: 'First geographic coordinate',
			},
			{
				displayName: 'Geocoord 2',
				name: 'geocoord2',
				type: 'number',
				default: 0,
				description: 'Second geographic coordinate',
			},
			{
				displayName: 'In Use By Name or ID',
				name: 'inuseby',
				type: 'options',
				typeOptions: {
					loadOptionsDependsOn: ['updateFields.client_id'],
					loadOptionsMethod: 'getClientUsers',
				},
				default: '',
				description: 'User who is using this site. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Inactive',
				name: 'inactive',
				type: 'boolean',
				default: false,
				description: 'Whether the site is inactive',
			},
			{
				displayName: 'Invoice Address Is Delivery',
				name: 'invoice_address_isdelivery',
				type: 'boolean',
				default: false,
				description: 'Whether invoice address is the same as delivery address',
			},
			{
				displayName: 'Is Invoice Site',
				name: 'isinvoicesite',
				type: 'boolean',
				default: false,
				description: 'Whether this is an invoice site',
			},
			{
				displayName: 'Is Stock Location',
				name: 'isstocklocation',
				type: 'boolean',
				default: false,
				description: 'Whether this site is a stock location',
			},
			{
				displayName: 'LDAP String',
				name: 'ldapstring',
				type: 'string',
				default: '',
				description: 'LDAP connection string',
			},
			{
				displayName: 'Message Group ID',
				name: 'messagegroup_id',
				type: 'number',
				default: 0,
				description: 'Message group ID for notifications',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'The name of the site',
			},
			{
				displayName: 'Notes',
				name: 'notes',
				type: 'string',
				typeOptions: {
					alwaysOpenEditWindow: true,
				},
				default: '',
				description: 'Notes about the site',
			},
			{
				displayName: 'Phone Number',
				name: 'phonenumber',
				type: 'string',
				default: '',
				description: 'Phone number for the site',
			},
			{
				displayName: 'Phone Number Int',
				name: 'sitephonenumberint',
				type: 'number',
				default: 0,
				description: 'Integer representation of phone number',
			},
			{
				displayName: 'Reference Number',
				name: 'refnumber',
				type: 'number',
				default: 0,
				description: 'Reference number for the site',
			},
			{
				displayName: 'Regional Director Name or ID',
				name: 'regionaldirector',
				type: 'options',
				typeOptions: {
					loadOptionsDependsOn: ['updateFields.client_id'],
					loadOptionsMethod: 'getClientUsers',
				},
				default: '',
				description: 'User for regional director. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Seriousness Level',
				name: 'seriousnesslevel',
				type: 'number',
				default: 0,
				description: 'Seriousness level for incidents',
			},
			{
				displayName: 'Site Date Format',
				name: 'sitedateformat',
				type: 'number',
				default: 0,
				description: 'Date format preference for the site',
			},
			{
				displayName: 'Site Time Offset',
				name: 'sitetimeoffset',
				type: 'number',
				default: 0,
				description: 'Time offset for the site in hours',
			},
			{
				displayName: 'SLA ID',
				name: 'sla_id',
				type: 'number',
				default: 0,
				description: 'Service Level Agreement ID',
			},
			{
				displayName: 'Stopped',
				name: 'stopped',
				type: 'number',
				default: 0,
				description: 'Whether the site is stopped (0 = active, 1 = stopped)',
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				description: 'Timezone for the site',
			},
			{
				displayName: 'To Domain',
				name: 'todomain',
				type: 'string',
				default: '',
				description: 'Domain to redirect to',
			},
		],
	},
];