import { INodeProperties } from 'n8n-workflow';

export const getAllDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['users'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['users'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['users'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Active Inactive',
				name: 'activeinactive',
				type: 'string',
				default: '',
				description: 'Takes two comma-separated values, the first sets includeactive ' + 
							'and the second sets includeinactive',
			},
			{
				displayName: 'Advanced Search',
				name: 'advanced_search',
				type: 'string',
				default: '',
				description: 'Advanced search parameters',
			},
			{
				displayName: 'All Approvers',
				name: 'allapprovers',
				type: 'boolean',
				default: false,
				description: 'Whether to add an OR condition to show all Users that are approvers ' +
							'in the response',
			},
			{
				displayName: 'Approvers Only',
				name: 'approvers_only',
				type: 'boolean',
				default: false,
				description: 'Whether to include only users that are an approver in the response',
			},
			{
				displayName: 'Asset ID',
				name: 'asset_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users assigned to a particular asset',
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users belonging to a particular client',
			},
			{
				displayName: 'Contract ID',
				name: 'contract_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users assigned to a particular device application type',
			},
			{
				displayName: 'Department ID',
				name: 'department_id',
				type: 'number',
				default: 0,
				description: 'Filter Users belonging to a particular department',
			},
			{
				displayName: 'Exclude Agents',
				name: 'exclude_agents',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude users that are also an agent in the response',
			},
			{
				displayName: 'Exclude Default Site Users',
				name: 'exclude_defaultsiteusers',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude default site users',
			},
			{
				displayName: 'Exclude General User',
				name: 'exclude_generaluser',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude general users in the response',
			},
			{
				displayName: 'ID Only',
				name: 'idonly',
				type: 'boolean',
				default: false,
				description: 'Whether to return only the ID field (User ID) of the Users ' +
							'(Not compatible with Pagination)',
			},
			{
				displayName: 'Include Active',
				name: 'includeactive',
				type: 'boolean',
				default: false,
				description: 'Whether to include users that are active in the response',
			},
			{
				displayName: 'Include Billing Info',
				name: 'includebillinginfo',
				type: 'boolean',
				default: false,
				description: 'Whether to include billing information in the response',
			},
			{
				displayName: 'Include Custom Fields',
				name: 'include_custom_fields',
				type: 'string',
				default: '',
				description: 'Comma-separated list of Custom Field IDs to include in the response',
			},
			{
				displayName: 'Include Inactive',
				name: 'includeinactive',
				type: 'boolean',
				default: false,
				description: 'Whether to include users that are inactive in the response',
			},
			{
				displayName: 'Include Name',
				name: 'includename',
				type: 'boolean',
				default: false,
				description: 'Whether to include user names in the response',
			},
			{
				displayName: 'Include Non Service Account',
				name: 'includenonserviceaccount',
				type: 'boolean',
				default: false,
				description: 'Whether to include users that are a non-service account in the response',
			},
			{
				displayName: 'Include Notes',
				name: 'includenotes',
				type: 'boolean',
				default: false,
				description: 'Whether to include user notes in the response',
			},
			{
				displayName: 'Include Service Account',
				name: 'includeserviceaccount',
				type: 'boolean',
				default: false,
				description: 'Whether to include users that are a service account in the response',
			},
			{
				displayName: 'Integration Type',
				name: 'integration_type',
				type: 'options',
				options: [
					{
						name: 'Azure',
						value: 'azure',
					},
					{
						name: 'Okta',
						value: 'okta',
					},
				],
				default: 'azure',
				description: 'Filter on Users that belong to an integration - ' +
							'Possible values are okta and azure',
			},
			{
				displayName: 'Is 3CX Call',
				name: 'is3cxcall',
				type: 'boolean',
				default: false,
				description: 'Whether to filter for 3CX call users',
			},
			{
				displayName: 'Is Followers',
				name: 'is_followers',
				type: 'boolean',
				default: false,
				description: 'Whether to filter for followers',
			},
			{
				displayName: 'Last Update From Date',
				name: 'lastupdatefromdate',
				type: 'boolean',
				default: false,
				description: 'Whether to include the field lastupdatefromdate in the response',
			},
			{
				displayName: 'Last Update To Date',
				name: 'lastupdatetodate',
				type: 'boolean',
				default: false,
				description: 'Whether to include the field lastupdatetodate in the response',
			},
			{
				displayName: 'Licence ID',
				name: 'licence_id',
				type: 'number',
				default: 0,
				description: 'Filter by licence ID',
			},
			{
				displayName: 'Linked To User ID',
				name: 'linked_to_user_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users that are linked to the specified User ID',
			},
			{
				displayName: 'List Agent User First',
				name: 'listagentuserfirst',
				type: 'boolean',
				default: false,
				description: 'Whether to order by users that are also agents first in the response',
			},
			{
				displayName: 'My All Customers',
				name: 'myallcustomers',
				type: 'boolean',
				default: false,
				description: 'Whether to include all customers',
			},
			{
				displayName: 'My Area',
				name: 'myarea',
				type: 'boolean',
				default: false,
				description: 'Whether to include only Users that belong to your area in the response',
			},
			{
				displayName: 'My Department',
				name: 'mydepartment',
				type: 'boolean',
				default: false,
				description: 'Whether to include only Users that belong to your department ' +
							'in the response',
			},
			{
				displayName: 'My Site',
				name: 'mysite',
				type: 'boolean',
				default: false,
				description: 'Whether to include only Users that belong to your site in the response',
			},
			{
				displayName: 'My Site Contact',
				name: 'mysitecontact',
				type: 'boolean',
				default: false,
				description: 'Whether to include only Users that belong to your site contact ' +
							'in the response',
			},
			{
				displayName: 'My Top Level',
				name: 'mytoplevel',
				type: 'boolean',
				default: false,
				description: 'Whether to include only Users that belong to your top level ' +
							'in the response',
			},
			{
				displayName: 'Opportunity ID',
				name: 'opp_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users assigned to a particular opportunity',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'string',
				default: '',
				description: 'The name of the field to order by first',
			},
			{
				displayName: 'Order 2',
				name: 'order2',
				type: 'string',
				default: '',
				description: 'The name of the field to order by second',
			},
			{
				displayName: 'Order 3',
				name: 'order3',
				type: 'string',
				default: '',
				description: 'The name of the field to order by third',
			},
			{
				displayName: 'Order 4',
				name: 'order4',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fourth',
			},
			{
				displayName: 'Order 5',
				name: 'order5',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fifth',
			},
			{
				displayName: 'Order Desc',
				name: 'orderdesc',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on first order',
			},
			{
				displayName: 'Order Desc 2',
				name: 'orderdesc2',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on second order',
			},
			{
				displayName: 'Order Desc 3',
				name: 'orderdesc3',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on third order',
			},
			{
				displayName: 'Order Desc 4',
				name: 'orderdesc4',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fourth order',
			},
			{
				displayName: 'Order Desc 5',
				name: 'orderdesc5',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fifth order',
			},
			{
				displayName: 'Organisation ID',
				name: 'organisation_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users belonging to a particular organisation',
			},
			{
				displayName: 'Page Number',
				name: 'page_no',
				type: 'number',
				default: 0,
				description: 'When using Pagination, the page number to return',
			},
			{
				displayName: 'Page Size',
				name: 'page_size',
				type: 'number',
				default: 0,
				description: 'When using Pagination, the size of the page',
			},
			{
				displayName: 'Paginate',
				name: 'pageinate',
				type: 'boolean',
				default: false,
				description: 'Whether to use Pagination in the response',
			},
			{
				displayName: 'Role',
				name: 'role',
				type: 'number',
				default: 0,
				description: 'Filter by role ID',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filter by Users like your search string',
			},
			{
				displayName: 'Search Phone Numbers',
				name: 'search_phonenumbers',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by Users with a phone number like your search',
			},
			{
				displayName: 'Site ID',
				name: 'site_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users belonging to a particular site',
			},
			{
				displayName: 'Supplier ID',
				name: 'supplier_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users belonging to the specified supplier',
			},
			{
				displayName: 'Ticket Type ID',
				name: 'tickettype_id',
				type: 'number',
				default: 0,
				description: 'Filter by ticket type ID',
			},
			{
				displayName: 'Top Level ID',
				name: 'toplevel_id',
				type: 'number',
				default: 0,
				description: 'Filter by Users belonging to a particular top level',
			},
		],
	},
];