import { INodeProperties } from 'n8n-workflow';

export const getAllDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'] } },
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Agent ID',
		name: 'agentId',
		type: 'number',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'] } },
		default: 0,
		description: 'Filter by agent ID',
	},
	{
		displayName: 'Team ID',
		name: 'teamId',
		type: 'number',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'] } },
		default: 0,
		description: 'Filter by team ID',
	},
	{
		displayName: 'Department ID',
		name: 'departmentId',
		type: 'number',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'] } },
		default: 0,
		description: 'Filter by department ID',
	},
	{
		displayName: 'Group ID',
		name: 'groupId',
		type: 'number',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'] } },
		default: 0,
		description: 'Filter by group ID',
	},
	{
		displayName: 'Show All',
		name: 'showAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'] } },
		default: false,
		description: 'Include all canned text entries',
	},
	{
		displayName: 'Ticket Only',
		name: 'ticketOnly',
		type: 'boolean',
		displayOptions: { show: { resource: ['cannedText'], operation: ['getAll'] } },
		default: false,
		description: 'Return ticket-only canned text',
	},
];
