import { INodeProperties } from 'n8n-workflow';

export const getALLDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['assets'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['assets'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['assets'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Active/Inactive',
				name: 'activeinactive',
				type: 'string',
				default: '',
				description: 'Filter on active/inactive assets - comma-separated, first value being true or false for active, second for inactive',
			},
			{
				displayName: 'Advanced Search',
				name: 'advanced_search',
				type: 'string',
				default: '',
				description: 'Advanced search string',
			},
			{
				displayName: 'Asset Group ID',
				name: 'assetgroup_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets belonging to a particular Asset group',
			},
			{
				displayName: 'Asset Groups',
				name: 'assetgroups',
				type: 'string',
				default: '',
				description: 'Filter Assets on asset groups, comma-separated IDs',
			},
			{
				displayName: 'Asset Statuses',
				name: 'assetstatuses',
				type: 'string',
				default: '',
				description: 'Filter Assets on asset statuses, comma-separated IDs',
			},
			{
				displayName: 'Asset Type',
				name: 'assettype',
				type: 'number',
				default: 0,
				description: 'Filter by specific asset type ID',
			},
			{
				displayName: 'Asset Type ID',
				name: 'assettype_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets belonging to a particular Asset type',
			},
			{
				displayName: 'Asset Types',
				name: 'assettypes',
				type: 'string',
				default: '',
				description: 'Filter Assets on asset types, comma-separated IDs',
			},
			{
				displayName: 'Assets',
				name: 'assets',
				type: 'string',
				default: '',
				description: 'Filter on specific asset IDs, comma-separated',
			},
			{
				displayName: 'Bookmarked',
				name: 'bookmarked',
				type: 'boolean',
				default: false,
				description: 'Whether to include only Assets that are bookmarked in the response',
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets belonging to a particular client',
			},
			{
				displayName: 'Columns ID',
				name: 'columns_id',
				type: 'number',
				default: 0,
				description: 'The column profile ID',
			},
			{
				displayName: 'Consignable',
				name: 'consignable',
				type: 'boolean',
				default: false,
				description: 'Whether to include only the Assets that are consignable in the response',
			},
			{
				displayName: 'Consignment ID',
				name: 'consignment_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets consignment ID',
			},
			{
				displayName: 'Contract ID',
				name: 'contract_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets assigned to a particular contract',
			},
			{
				displayName: 'Contract ID Adding To',
				name: 'contract_id_adding_to',
				type: 'number',
				default: 0,
				description: 'Include the billing period of the linked contract ID in the response',
			},
			{
				displayName: 'Domotz Agents',
				name: 'domotzagents',
				type: 'boolean',
				default: false,
				description: 'Whether to include only Assets with a linked Domotz agent in the response',
			},
			{
				displayName: 'Exclude These',
				name: 'excludethese',
				type: 'string',
				default: '',
				description: 'Returns Assets based on the exclusion of these Asset IDs, comma-separated',
			},
			{
				displayName: 'Global Search ID',
				name: 'globalSearchID',
				type: 'string',
				default: '',
				description: 'Global search ID filter',
			},
			{
				displayName: 'ID Only',
				name: 'idonly',
				type: 'boolean',
				default: false,
				description: 'Whether to include only the Asset ID in the response',
			},
			{
				displayName: 'Include Active',
				name: 'includeactive',
				type: 'boolean',
				default: false,
				description: 'Whether to include active Assets in the response',
			},
			{
				displayName: 'Include Allowed Status',
				name: 'includeallowedstatus',
				type: 'boolean',
				default: false,
				description: 'Whether to include the Asset column tallowallstatus in the response',
			},
			{
				displayName: 'Include Asset Fields',
				name: 'includeassetfields',
				type: 'boolean',
				default: false,
				description: 'Whether to include asset fields in the response - must also specify assettype_id at the same time',
			},
			{
				displayName: 'Include Children',
				name: 'includechildren',
				type: 'boolean',
				default: false,
				description: 'Whether to include child Assets in the response',
			},
			{
				displayName: 'Include Columns',
				name: 'includecolumns',
				type: 'boolean',
				default: false,
				description: 'Whether to include column details in the response',
			},
			{
				displayName: 'Include Custom Fields',
				name: 'include_custom_fields',
				type: 'multiOptions',
				typeOptions: {
					loadOptionsMethod: 'getCustomFields',
				},
				default: [],
				description: 'Custom Field IDs to include in the response. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Include Inactive',
				name: 'includeinactive',
				type: 'boolean',
				default: false,
				description: 'Whether to include inactive Assets in the response',
			},
			{
				displayName: 'Include Services',
				name: 'includeservices',
				type: 'boolean',
				default: false,
				description: 'Whether to include Assets linked service IDs in the response',
			},
			{
				displayName: 'Include User',
				name: 'includeuser',
				type: 'boolean',
				default: false,
				description: 'Whether to include user details in the response',
			},
			{
				displayName: 'Integration Tenant IDs',
				name: 'integration_tenantids',
				type: 'string',
				default: '',
				description: 'Filter by integration tenant IDs (comma-separated)',
			},
			{
				displayName: 'Integration Type',
				name: 'integration_type',
				type: 'options',
				options: [
					{
						name: 'Addigy',
						value: 'addigy',
					},
					{
						name: 'Atera RMM',
						value: 'aterarmm',
					},
					{
						name: 'ConnectWise Automate',
						value: 'connectwiseautomate',
					},
					{
						name: 'Datto',
						value: 'datto',
					},
					{
						name: 'Domotz',
						value: 'domotz',
					},
					{
						name: 'Liongard',
						value: 'liongard',
					},
					{
						name: 'Ninja RMM',
						value: 'ninjarmm',
					},
					{
						name: 'PassPortal',
						value: 'passportal',
					},
					{
						name: 'ServiceNow',
						value: 'snow',
					},
					{
						name: 'Syncro MSP',
						value: 'syncromsp',
					},
				],
				default: 'addigy',
				description: 'Filter on which integration the Asset was imported through',
			},
			{
				displayName: 'Inventory Number',
				name: 'inventory_number',
				type: 'string',
				default: '',
				description: 'Filter by specific inventory number',
			},
			{
				displayName: 'Is Logon Behalf View',
				name: 'islogonbehalfview',
				type: 'boolean',
				default: false,
				description: 'Whether this is a logon behalf view',
			},
			{
				displayName: 'Item ID',
				name: 'item_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets item ID',
			},
			{
				displayName: 'Item Stock ID',
				name: 'itemstock_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets item stock ID',
			},
			{
				displayName: 'KB ID',
				name: 'kb_id',
				type: 'number',
				default: 0,
				description: 'Filter by knowledge base ID',
			},
			{
				displayName: 'Last Update From Date',
				name: 'lastupdatefromdate',
				type: 'boolean',
				default: false,
				description: 'Whether to include the field lastupdatefromdate in the response',
			},
			{
				displayName: 'Last Update To Date',
				name: 'lastupdatetodate',
				type: 'boolean',
				default: false,
				description: 'Whether to include the field lastupdatetodate in the response',
			},
			{
				displayName: 'Licence ID',
				name: 'licence_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets assigned to a particular licence',
			},
			{
				displayName: 'Linked To ID',
				name: 'linkedto_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets linked to a particular Asset',
			},
			{
				displayName: 'Linked to Ticket',
				name: 'linked_to_ticket',
				type: 'boolean',
				default: false,
				description: 'Whether to filter assets linked to tickets',
			},
			{
				displayName: 'Mine',
				name: 'mine',
				type: 'boolean',
				default: false,
				description: 'Whether to include only the Assets that belong to yourself in the response',
			},
			{
				displayName: 'My Site',
				name: 'mysite',
				type: 'boolean',
				default: false,
				description: 'Whether to include only the Assets that belong to your site in the response',
			},
			{
				displayName: 'No Icon',
				name: 'noicon',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude the Asset icon in the response',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'string',
				default: '',
				description: 'The name of the field to order by first',
			},
			{
				displayName: 'Order 2',
				name: 'order2',
				type: 'string',
				default: '',
				description: 'The name of the field to order by second',
			},
			{
				displayName: 'Order 3',
				name: 'order3',
				type: 'string',
				default: '',
				description: 'The name of the field to order by third',
			},
			{
				displayName: 'Order 4',
				name: 'order4',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fourth',
			},
			{
				displayName: 'Order 5',
				name: 'order5',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fifth',
			},
			{
				displayName: 'Order Desc',
				name: 'orderdesc',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on first order',
			},
			{
				displayName: 'Order Desc 2',
				name: 'orderdesc2',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on second order',
			},
			{
				displayName: 'Order Desc 3',
				name: 'orderdesc3',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on third order',
			},
			{
				displayName: 'Order Desc 4',
				name: 'orderdesc4',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fourth order',
			},
			{
				displayName: 'Order Desc 5',
				name: 'orderdesc5',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fifth order',
			},
			{
				displayName: 'Page Number',
				name: 'page_no',
				type: 'number',
				default: 0,
				description: 'When using pagination, the page number to return',
			},
			{
				displayName: 'Page Size',
				name: 'page_size',
				type: 'number',
				default: 0,
				typeOptions: {
					maxValue: 100,
				},
				description: 'When using pagination, the size of the page (max: 100)',
			},
			{
				displayName: 'Paginate',
				name: 'pageinate',
				type: 'boolean',
				default: false,
				description: 'Whether to use pagination in the response',
			},
			{
				displayName: 'Previously Selected',
				name: 'previously_selected',
				type: 'boolean',
				default: false,
				description: 'Whether to include the most recent dateoccured field from a linked ticket in the response',
			},
			{
				displayName: 'Previously Selected Client ID',
				name: 'previously_selected_client_id',
				type: 'number',
				default: 0,
				description: 'Filter previously_selected by client ID',
			},
			{
				displayName: 'Previously Selected Site ID',
				name: 'previously_selected_site_id',
				type: 'number',
				default: 0,
				description: 'Filter previously_selected by site ID',
			},
			{
				displayName: 'Previously Selected User ID',
				name: 'previously_selected_user_id',
				type: 'number',
				default: 0,
				description: 'Filter previously_selected by user ID',
			},
			{
				displayName: 'Sales Order ID',
				name: 'salesorder_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets sales order ID',
			},
			{
				displayName: 'Sales Order Line',
				name: 'salesorder_line',
				type: 'number',
				default: 0,
				description: 'Filter by Assets sales order line ID',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filters response based on the search string',
			},
			{
				displayName: 'Search Inventory Number Only',
				name: 'search_inventory_number_only',
				type: 'boolean',
				default: false,
				description: 'Whether to search only on inventory number in the search string',
			},
			{
				displayName: 'Service ID',
				name: 'service_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets belonging to a particular service',
			},
			{
				displayName: 'Service IDs',
				name: 'service_ids',
				type: 'string',
				default: '',
				description: 'Filter Assets on service IDs, comma-separated IDs',
			},
			{
				displayName: 'Site ID',
				name: 'site_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets belonging to a particular site',
			},
			{
				displayName: 'Stock Bin ID',
				name: 'stockbin_id',
				type: 'number',
				default: 0,
				description: 'Filter by stock bin ID',
			},
			{
				displayName: 'Stock Bin IDs',
				name: 'stockbin_ids',
				type: 'string',
				default: '',
				description: 'Filter by stock bin IDs (comma-separated)',
			},
			{
				displayName: 'Supplier Contract ID',
				name: 'supplier_contract_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets assigned to a particular supplier contract',
			},
			{
				displayName: 'Supplier Contracts',
				name: 'suppliercontracts',
				type: 'string',
				default: '',
				description: 'Filter Assets on supplier contracts, comma-separated IDs',
			},
			{
				displayName: 'Supplier ID',
				name: 'supplier_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets belonging to a particular supplier',
			},
			{
				displayName: 'Ticket ID',
				name: 'ticket_id',
				type: 'number',
				default: 0,
				description: 'Filter by Assets belonging to a particular ticket',
			},
			{
				displayName: 'Ticket Type ID',
				name: 'tickettype_id',
				type: 'number',
				default: 0,
				description: 'Filter by ticket type ID',
			},
			{
				displayName: 'User ID',
				name: 'user_id',
				type: 'number',
				default: 0,
				description: 'Filter by specific user ID',
			},
			{
				displayName: 'Username',
				name: 'username',
				type: 'string',
				default: '',
				description: 'Filters by the specified username',
			},
		],
	},
];