import { INodeProperties } from 'n8n-workflow';

export const getByIdDescription: INodeProperties[] = [
	{
		displayName: 'Ticket ID',
		name: 'ticketId',
		type: 'number',
		required: true,
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['getById'],
			},
		},
		default: 0,
		description: 'The ID of the ticket to retrieve',
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['getById'],
			},
		},
	options: [
			{
				displayName: 'AMail Entry ID',
				name: 'amailentryid',
				type: 'string',
				default: '',
				description: 'AMail entry ID parameter',
			},
			{
				displayName: 'Assigned To',
				name: 'assignedto',
				type: 'number',
				default: 0,
				description: 'Filter by assigned to agent ID',
			},
			{
				displayName: 'Consignable Lines',
				name: 'consignablelines',
				type: 'boolean',
				default: false,
				description: 'Whether to include consignable lines',
			},
			{
				displayName: 'Debug',
				name: 'debug',
				type: 'boolean',
				default: false,
				description: 'Whether to include debug information in the response',
			},
			{
				displayName: 'Do Database Lookup',
				name: 'dodatabaselookup',
				type: 'boolean',
				default: false,
				description: 'Whether to perform database lookup',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				description: 'Email address filter',
			},
			{
				displayName: 'Include Agent Details',
				name: 'includeagent',
				type: 'boolean',
				default: false,
				description: 'Whether to include agent details in the response',
			},
			{
				displayName: 'Include Auditing',
				name: 'include_auditing',
				type: 'boolean',
				default: false,
				description: 'Whether to include auditing in the response',
			},
			{
				displayName: 'Include Child IDs',
				name: 'includechildids',
				type: 'boolean',
				default: false,
				description: 'Whether to include child ticket IDs',
			},
			{
				displayName: 'Include Details',
				name: 'includedetails',
				type: 'boolean',
				default: true,
				description: 'Whether to include extra objects in the response',
			},
			{
				displayName: 'Include Last Action',
				name: 'includelastaction',
				type: 'boolean',
				default: false,
				description: 'Whether to include the last action in the response',
			},
			{
				displayName: 'Include Last Appointment',
				name: 'includelastappointment',
				type: 'boolean',
				default: false,
				description: 'Whether to include the last appointment in the response',
			},
			{
				displayName: 'Include Linked Objects',
				name: 'includelinkedobjects',
				type: 'boolean',
				default: false,
				description: 'Whether to include linked objects in the response',
			},
			{
				displayName: 'Include Next Appointment',
				name: 'includenextappointment',
				type: 'boolean',
				default: false,
				description: 'Whether to include the next appointment in the response',
			},
			{
				displayName: 'Include Parent Change Info',
				name: 'includeparentchangeinfo',
				type: 'boolean',
				default: false,
				description: 'Whether to include parent change information',
			},
			{
				displayName: 'Include Parent Subject',
				name: 'includeparentsubject',
				type: 'boolean',
				default: false,
				description: 'Whether to include parent subject',
			},
			{
				displayName: 'Include Seen By',
				name: 'includeseenby',
				type: 'boolean',
				default: false,
				description: 'Whether to include seen by information',
			},
			{
				displayName: 'Is Detail Screen',
				name: 'isdetailscreen',
				type: 'boolean',
				default: false,
				description: 'Whether this is for detail screen',
			},
			{
				displayName: 'Is Halo Link',
				name: 'ishalolink',
				type: 'boolean',
				default: false,
				description: 'Whether this is a Halo link request',
			},
			{
				displayName: 'Is Portal',
				name: 'is_portal',
				type: 'boolean',
				default: false,
				description: 'Whether this is for portal access',
			},
			{
				displayName: 'Is Preview',
				name: 'ispreview',
				type: 'boolean',
				default: false,
				description: 'Whether this is for preview mode',
			},
			{
				displayName: 'Is Teams',
				name: 'isteams',
				type: 'boolean',
				default: false,
				description: 'Whether to return only teams tickets in the response',
			},
			{
				displayName: 'No Cache',
				name: 'nocache',
				type: 'boolean',
				default: false,
				description: 'Whether to cache the response',
			},
			{
				displayName: 'Subject',
				name: 'subject',
				type: 'string',
				default: '',
				description: 'Subject filter',
			},
			{
				displayName: 'Ticket ID Only',
				name: 'ticketidonly',
				type: 'boolean',
				default: false,
				description: 'Whether to include only details related to the ticket specified in the response',
			},
			{
				displayName: 'UTC Offset',
				name: 'utcoffset',
				type: 'number',
				default: 0,
				typeOptions: {
					numberPrecision: 2,
				},
				description: 'Adds an offset to the UTC date',
			},
		],
	},
];