import { INodeProperties } from 'n8n-workflow';

export const getAllDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: false,
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 },
		default: 50,
	},
	{
		displayName: 'Department ID',
		name: 'departmentId',
		type: 'number',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: 0,
	},
	{
		displayName: 'Type',
		name: 'teamType',
		type: 'options',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		options: [
			{ name: 'All', value: '' },
			{ name: 'Tickets (reqs)', value: 'reqs' },
			{ name: 'Opportunities (opps)', value: 'opps' },
			{ name: 'Projects (prjs)', value: 'prjs' },
		],
		default: '',
		description: 'Filter by team domain',
	},
	{
		displayName: 'Team IDs',
		name: 'teamIds',
		type: 'string',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: '',
		description: 'Comma-separated team IDs',
	},
	{
		displayName: 'Show All',
		name: 'showAll',
		type: 'boolean',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: false,
		description: 'Admin override to show all teams',
	},
	{
		displayName: 'Member Only',
		name: 'memberOnly',
		type: 'boolean',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: false,
	},
	{
		displayName: 'My Teams Only',
		name: 'myTeamsOnly',
		type: 'boolean',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: false,
	},
	{
		displayName: 'Can Edit Only',
		name: 'canEditOnly',
		type: 'boolean',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: false,
	},
	{
		displayName: 'Show Counts',
		name: 'showCounts',
		type: 'boolean',
		displayOptions: { show: { resource: ['teams'], operation: ['getAll'] } },
		default: false,
	},
];
