import { INodeProperties } from 'n8n-workflow';

export const getALLDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getAll'],
			},
		},
	options: [
		{
			displayName: 'Active Inactive',
			name: 'activeinactive',
			type: 'string',
			default: '',
			description: 'Takes two comma-separated values, the first sets includeactive and the second sets includeinactive',
		},
		{
			displayName: 'Appointment Screen',
			name: 'appointmentscreen',
			type: 'boolean',
			default: false,
			description: 'Whether to filter for appointment screen agents',
		},
		{
			displayName: 'Basic Fields Only',
			name: 'basic_fields_only',
			type: 'boolean',
			default: false,
			description: 'Whether to reduce the number of fields returned',
		},
		{
			displayName: 'Can Edit Only',
			name: 'can_edit_only',
			type: 'boolean',
			default: false,
			description: 'Whether to filter on agents that you have permission to edit',
		},
		{
			displayName: 'Client ID',
			name: 'client_id',
			type: 'number',
			default: 0,
			description: 'Filter by agents belonging to a particular client',
		},
		{
			displayName: 'Client ID Override',
			name: 'clientidoverride',
			type: 'string',
			default: '',
			description: 'Override client ID for filtering',
		},
		{
			displayName: 'Department ID',
			name: 'department_id',
			type: 'number',
			default: 0,
			description: 'Filter agents belonging to a particular department',
		},
		{
			displayName: 'Departments',
			name: 'departments',
			type: 'string',
			default: '',
			description: 'Filter on agents that belong to a department (comma-separated)',
		},
		{
			displayName: 'Domain',
			name: 'domain',
			type: 'options',
			options: [
				{
					name: 'Opportunities',
					value: 'opps',
				},
				{
					name: 'Projects',
					value: 'prjs',
				},
				{
					name: 'Requests',
					value: 'reqs',
				},
			],
			default: 'opps',
			description: 'Filter on agent permissions',
		},
		{
			displayName: 'Exchange Calendars',
			name: 'exchangecalendars',
			type: 'boolean',
			default: false,
			description: 'Whether to filter on agents that have exchange calendars synced',
		},
		{
			displayName: 'Exclude Agent',
			name: 'excludeAgent',
			type: 'number',
			default: 0,
			description: 'Exclude agent with specified ID',
		},
		{
			displayName: 'Exclude Membership Info',
			name: 'exclude_membership_info',
			type: 'boolean',
			default: false,
			description: 'Whether to remove team and department membership information from the response',
		},
		{
			displayName: 'Force Qual Match',
			name: 'forcequalmatch',
			type: 'boolean',
			default: false,
			description: 'Whether to force qualification match',
		},
		{
			displayName: 'Include API Agents',
			name: 'includeapiagents',
			type: 'boolean',
			default: false,
			description: 'Whether to include API agents in the response',
		},
		{
			displayName: 'Include Disabled',
			name: 'includedisabled',
			type: 'string',
			default: '',
			description: 'Include agents that are inactive in the response',
		},
		{
			displayName: 'Include Enabled',
			name: 'includeenabled',
			type: 'string',
			default: '',
			description: 'Include agents that are active in the response',
		},
		{
			displayName: 'Include Membership Info',
			name: 'include_membership_info',
			type: 'boolean',
			default: false,
			description: 'Whether to always include team and department membership information in the response',
		},
		{
			displayName: 'Include Named Count',
			name: 'includenamedcount',
			type: 'boolean',
			default: false,
			description: 'Whether to include the count of the number of agents in the response',
		},
		{
			displayName: 'Include Roles',
			name: 'includeroles',
			type: 'boolean',
			default: false,
			description: 'Whether to include agent roles in the response',
		},
		{
			displayName: 'Include Status',
			name: 'includestatus',
			type: 'boolean',
			default: false,
			description: 'Whether to include agent status in the response',
		},
		{
			displayName: 'Include Unassigned',
			name: 'includeunassigned',
			type: 'string',
			default: '',
			description: 'Include the unassigned agent in the response',
		},
		{
			displayName: 'Integration Type',
			name: 'integration_type',
			type: 'options',
			options: [
				{
					name: 'Okta',
					value: 'okta',
				},
			],
			default: 'okta',
			description: 'Filter on agents that belong to an integration',
		},
		{
			displayName: 'Is Agent Cache',
			name: 'is_agent_cache',
			type: 'boolean',
			default: false,
			description: 'Whether to use special behaviour for agent app agent cache build',
		},
		{
			displayName: 'Line Managed Only',
			name: 'linemanagedonly',
			type: 'boolean',
			default: false,
			description: 'Whether to filter on agents that have a line manager',
		},
		{
			displayName: 'Linking Agents',
			name: 'linkingagents',
			type: 'boolean',
			default: false,
			description: 'Whether to filter for linking agents',
		},
		{
			displayName: 'Load Cache',
			name: 'loadcache',
			type: 'boolean',
			default: false,
			description: 'Whether to load cache',
		},
		{
			displayName: 'Online Statuses',
			name: 'onlinestatuses',
			type: 'string',
			default: '',
			description: 'Filter on agents that have a certain online status (comma-separated)',
		},
		{
			displayName: 'Order',
			name: 'order',
			type: 'string',
			default: '',
			description: 'Field to order results by',
		},
		{
			displayName: 'Order 2',
			name: 'order2',
			type: 'string',
			default: '',
			description: 'Second field to order results by',
		},
		{
			displayName: 'Order 3',
			name: 'order3',
			type: 'string',
			default: '',
			description: 'Third field to order results by',
		},
		{
			displayName: 'Order 4',
			name: 'order4',
			type: 'string',
			default: '',
			description: 'Fourth field to order results by',
		},
		{
			displayName: 'Order 5',
			name: 'order5',
			type: 'string',
			default: '',
			description: 'Fifth field to order results by',
		},
		{
			displayName: 'Order Desc',
			name: 'orderdesc',
			type: 'boolean',
			default: false,
			description: 'Whether to order in descending order',
		},
		{
			displayName: 'Order Desc 2',
			name: 'orderdesc2',
			type: 'boolean',
			default: false,
			description: 'Whether to order second field in descending order',
		},
		{
			displayName: 'Order Desc 3',
			name: 'orderdesc3',
			type: 'boolean',
			default: false,
			description: 'Whether to order third field in descending order',
		},
		{
			displayName: 'Order Desc 4',
			name: 'orderdesc4',
			type: 'boolean',
			default: false,
			description: 'Whether to order fourth field in descending order',
		},
		{
			displayName: 'Order Desc 5',
			name: 'orderdesc5',
			type: 'boolean',
			default: false,
			description: 'Whether to order fifth field in descending order',
		},
		{
			displayName: 'Page Number',
			name: 'page_no',
			type: 'number',
			default: 0,
			description: 'Page number for pagination',
		},
		{
			displayName: 'Page Size',
			name: 'page_size',
			type: 'number',
			default: 0,
			description: 'Page size for pagination',
		},
		{
			displayName: 'Paginate',
			name: 'pageinate',
			type: 'boolean',
			default: false,
			description: 'Whether to paginate results',
		},
		{
			displayName: 'Qualifications',
			name: 'qualifications',
			type: 'string',
			default: '',
			description: 'Filter by agents with certain qualifications (comma-separated)',
		},
		{
			displayName: 'Reassign',
			name: 'reassign',
			type: 'boolean',
			default: false,
			description: 'Whether to filter on agents that can assign to agents in sections that agent is not a member of',
		},
		{
			displayName: 'Remote Agent Type',
			name: 'remoteagenttype',
			type: 'options',
			options: [
				{
					name: 'BeyondTrust',
					value: 'beyondtrust',
				},
				{
					name: 'LogMeIn',
					value: 'logmein',
				},
			],
			default: 'beyondtrust',
			description: 'Filter on agent invite permissions',
		},
		{
			displayName: 'Remote Agents',
			name: 'remoteagents',
			type: 'boolean',
			default: false,
			description: 'Whether to filter on agent invite permissions',
		},
		{
			displayName: 'Role',
			name: 'role',
			type: 'string',
			default: '',
			description: 'Filter by agents who have a particular role (requires an int passed as a string)',
		},
		{
			displayName: 'Search',
			name: 'search',
			type: 'string',
			default: '',
			description: 'Filter by agents with a name, email address or telephone number like your search',
		},
		{
			displayName: 'Shift Agents Only',
			name: 'shiftagentsonly',
			type: 'boolean',
			default: false,
			description: 'Whether to filter for shift agents only',
		},
		{
			displayName: 'Show All',
			name: 'showall',
			type: 'boolean',
			default: false,
			description: 'Whether to override org restrictions for main search (admin only)',
		},
		{
			displayName: 'Show Counts',
			name: 'showcounts',
			type: 'boolean',
			default: false,
			description: 'Whether to include agent ticket counts in the response',
		},
		{
			displayName: 'Team',
			name: 'team',
			type: 'string',
			default: '',
			description: 'Filter by agents within a particular team',
		},
		{
			displayName: 'Team ID',
			name: 'team_id',
			type: 'number',
			default: 0,
			description: 'Filter by agents within a particular team ID',
		},
		{
			displayName: 'Teams',
			name: 'teams',
			type: 'string',
			default: '',
			description: 'Filter on agents that belong to a team (comma-separated)',
		},
		{
			displayName: 'This Agent Only',
			name: 'thisAgentOnly',
			type: 'boolean',
			default: false,
			description: 'Whether to only include your agent in the response',
		},
		{
			displayName: 'Ticket Area ID',
			name: 'ticketarea_id',
			type: 'number',
			default: 0,
			description: 'Only for showcounts - ticket area filter',
		},
		{
			displayName: 'Ticket Type ID',
			name: 'tickettype_id',
			type: 'number',
			default: 0,
			description: 'Filter by agents that have access to particular ticket types',
		},
		{
			displayName: 'View ID',
			name: 'view_id',
			type: 'number',
			default: 0,
			description: 'Only for showcounts - ticket view filter',
		},
		{
			displayName: 'With Email',
			name: 'withemail',
			type: 'boolean',
			default: false,
			description: 'Whether to filter on agents that have an email',
		},
	],
	},
];