import { INodeProperties } from 'n8n-workflow';

export const getALLDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['client'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['client'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['client'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Account Manager Only',
				name: 'accountmanageronly',
				type: 'boolean',
				default: false,
				description: 'Whether to include only clients that you are an account manager of in the response',
			},
			{
				displayName: 'Active Inactive',
				name: 'activeinactive',
				type: 'string',
				default: '',
				description: 'Takes two comma-separated values, the first sets includeactive and the second sets includeinactive',
			},
			{
				displayName: 'Advanced Search',
				name: 'advanced_search',
				type: 'string',
				default: '',
				description: 'Advanced search string',
			},
			{
				displayName: 'Azure Clients',
				name: 'azureclients',
				type: 'boolean',
				default: false,
				description: 'Whether to include only azure clients in the response',
			},
			{
				displayName: 'Call Plan',
				name: 'callplan',
				type: 'boolean',
				default: false,
				description: 'Whether to include only clients that have the field acalldate in the past in the response',
			},
			{
				displayName: 'Columns ID',
				name: 'columns_id',
				type: 'number',
				default: 0,
				description: 'The column profile ID',
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: '',
				description: 'Domain filter',
			},
			{
				displayName: 'Exclude Internal',
				name: 'exclude_internal',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude internal clients',
			},
			{
				displayName: 'GFI Clients',
				name: 'gficlients',
				type: 'boolean',
				default: false,
				description: 'Whether to include only GFI clients in the response',
			},
			{
				displayName: 'ID Only',
				name: 'idonly',
				type: 'boolean',
				default: false,
				description: 'Whether to return only the ID field (Area ID) of the Clients (Not compatible with Pagination)',
			},
			{
				displayName: 'Include Active',
				name: 'includeactive',
				type: 'boolean',
				default: false,
				description: 'Whether to include clients that are active in the response',
			},
			{
				displayName: 'Include Azure Tenants',
				name: 'includeazuretenants',
				type: 'boolean',
				default: false,
				description: 'Whether to include azure tenants in the response',
			},
			{
				displayName: 'Include Columns',
				name: 'includecolumns',
				type: 'boolean',
				default: false,
				description: 'Whether to include column details in the response',
			},
			{
				displayName: 'Include Custom Fields',
				name: 'include_custom_fields',
				type: 'string',
				default: '',
				description: 'Comma-separated list of Custom Field IDs to include in the response',
			},
			{
				displayName: 'Include Inactive',
				name: 'includeinactive',
				type: 'boolean',
				default: false,
				description: 'Whether to include clients that are inactive in the response',
			},
			{
				displayName: 'Include Invoice Template Name',
				name: 'includeinvoicetemplatename',
				type: 'boolean',
				default: false,
				description: 'Whether to include invoice template names in the response',
			},
			{
				displayName: 'Include Notes',
				name: 'includenotes',
				type: 'boolean',
				default: false,
				description: 'Whether to include client notes in the response',
			},
			{
				displayName: 'Include QBO Fields',
				name: 'includeqbofields',
				type: 'boolean',
				default: false,
				description: 'Whether to include QuickBooks Online fields in the response',
			},
			{
				displayName: 'Integration Tenant IDs',
				name: 'integration_tenantids',
				type: 'string',
				default: '',
				description: 'Comma-separated list of integration tenant IDs',
			},
			{
				displayName: 'Integration Type',
				name: 'integration_type',
				type: 'string',
				default: '',
				description: 'Integration type filter',
			},
			{
				displayName: 'Is Jira',
				name: 'isjira',
				type: 'boolean',
				default: false,
				description: 'Whether to filter for Jira clients',
			},
			{
				displayName: 'Is Sentinel',
				name: 'issentinel',
				type: 'boolean',
				default: false,
				description: 'Whether to include only sentinel clients in the response',
			},
			{
				displayName: 'Is ServiceNow',
				name: 'isservicenow',
				type: 'boolean',
				default: false,
				description: 'Whether to filter for ServiceNow clients',
			},
			{
				displayName: 'Last Update From Date',
				name: 'lastupdatefromdate',
				type: 'boolean',
				default: false,
				description: 'Whether to include the field lastupdatefromdate in the response',
			},
			{
				displayName: 'Last Update To Date',
				name: 'lastupdatetodate',
				type: 'boolean',
				default: false,
				description: 'Whether to include the field lastupdatetodate in the response',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'string',
				default: '',
				description: 'The name of the field to order by first',
			},
			{
				displayName: 'Order 2',
				name: 'order2',
				type: 'string',
				default: '',
				description: 'The name of the field to order by second',
			},
			{
				displayName: 'Order 3',
				name: 'order3',
				type: 'string',
				default: '',
				description: 'The name of the field to order by third',
			},
			{
				displayName: 'Order 4',
				name: 'order4',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fourth',
			},
			{
				displayName: 'Order 5',
				name: 'order5',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fifth',
			},
			{
				displayName: 'Order Desc',
				name: 'orderdesc',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on first order',
			},
			{
				displayName: 'Order Desc 2',
				name: 'orderdesc2',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on second order',
			},
			{
				displayName: 'Order Desc 3',
				name: 'orderdesc3',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on third order',
			},
			{
				displayName: 'Order Desc 4',
				name: 'orderdesc4',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fourth order',
			},
			{
				displayName: 'Order Desc 5',
				name: 'orderdesc5',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fifth order',
			},
			{
				displayName: 'Page Number',
				name: 'page_no',
				type: 'number',
				default: 0,
				description: 'When using Pagination, the page number to return',
			},
			{
				displayName: 'Page Size',
				name: 'page_size',
				type: 'number',
				default: 0,
				typeOptions: {
					maxValue: 100,
				},
				description: 'When using Pagination, the size of the page',
			},
			{
				displayName: 'Paginate',
				name: 'pageinate',
				type: 'boolean',
				default: false,
				description: 'Whether to use Pagination in the response',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filter by Customers like your search string',
			},
			{
				displayName: 'Search Name Only',
				name: 'search_name_only',
				type: 'string',
				default: '',
				description: 'Search by name only',
			},
			{
				displayName: 'Sentinel ID',
				name: 'sentinelid',
				type: 'number',
				default: 0,
				description: 'Filter by sentinel ID',
			},
			{
				displayName: 'Show Counts',
				name: 'showcounts',
				type: 'boolean',
				default: false,
				description: 'Whether to show record counts',
			},
			{
				displayName: 'Site Fields',
				name: 'sitefields',
				type: 'string',
				default: '',
				description: 'IDs of site fields to include in the response',
			},
			{
				displayName: 'Snow Account ID',
				name: 'snowaccountid',
				type: 'number',
				default: 0,
				description: 'ServiceNow account ID filter',
			},
			{
				displayName: 'Snow Clients',
				name: 'snowclients',
				type: 'boolean',
				default: false,
				description: 'Whether to include only snow clients in the response',
			},
			{
				displayName: 'Ticket Area ID',
				name: 'ticketarea_id',
				type: 'number',
				default: 0,
				description: 'Ticket area ID filter',
			},
			{
				displayName: 'Top Level ID',
				name: 'toplevel_id',
				type: 'number',
				default: 0,
				description: 'Filter by Customers belonging to a particular top level',
			},
			{
				displayName: 'View ID',
				name: 'view_id',
				type: 'number',
				default: 0,
				description: 'View ID filter',
			},
		],
	},
];