import { INodeProperties } from 'n8n-workflow';

export const getALLDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['getAll'],
			},
		},
	options: [
			{
				displayName: 'Advanced Search',
				name: 'advanced_search',
				type: 'string',
				default: '',
				description: 'Advanced search string',
			},
			{
				displayName: 'Agent',
				name: 'agent',
				type: 'string',
				default: '',
				description: 'Returns tickets based on Agent IDs in the array (comma-separated)',
			},
			{
				displayName: 'Agent ID',
				name: 'agent_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified agent',
			},
			{
				displayName: 'Alert Type',
				name: 'alerttype',
				type: 'string',
				default: '',
				description: 'Includes fninjaalertid field in the response - "ninjarmm" to use',
			},
			{
				displayName: 'Asset ID',
				name: 'asset_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified asset',
			},
			{
				displayName: 'Awaiting Input',
				name: 'awaitinginput',
				type: 'string',
				default: '',
				description: 'Filter by awaiting input status',
			},
			{
				displayName: 'Billable Only',
				name: 'billableonly',
				type: 'boolean',
				default: false,
				description: 'Whether to return only billable tickets',
			},
			{
				displayName: 'Billing Contract ID',
				name: 'billingcontractid',
				type: 'number',
				default: 0,
				description: 'Filter by billing contract ID',
			},
			{
				displayName: 'Billing Date',
				name: 'billing_date',
				type: 'string',
				default: '',
				description: 'Filter on billing date',
			},
			{
				displayName: 'Billing Type',
				name: 'billing_type',
				type: 'string',
				default: '',
				description: 'Filter on billing type',
			},
			{
				displayName: 'Calendar End Date',
				name: 'calendar_enddate',
				type: 'dateTime',
				default: '',
				description: 'Specifies the calendar search parameter for actions before this date',
			},
			{
				displayName: 'Calendar Start Date',
				name: 'calendar_startdate',
				type: 'dateTime',
				default: '',
				description: 'Specifies the calendar search parameter for actions after this date',
			},
			{
				displayName: 'Category 1',
				name: 'category_1',
				type: 'string',
				default: '',
				description: 'Returns tickets based on category 1 IDs in the array (comma-separated)',
			},
			{
				displayName: 'Category 2',
				name: 'category_2',
				type: 'string',
				default: '',
				description: 'Returns tickets based on category 2 IDs in the array (comma-separated)',
			},
			{
				displayName: 'Category 3',
				name: 'category_3',
				type: 'string',
				default: '',
				description: 'Returns tickets based on category 3 IDs in the array (comma-separated)',
			},
			{
				displayName: 'Category 4',
				name: 'category_4',
				type: 'string',
				default: '',
				description: 'Returns tickets based on category 4 IDs in the array (comma-separated)',
			},
			{
				displayName: 'CF Display Values Only',
				name: 'cf_display_values_only',
				type: 'boolean',
				default: false,
				description: 'Whether to use performant method to query custom fields (display values only)',
			},
			{
				displayName: 'Check My Tickets Only',
				name: 'checkmyticketsonly',
				type: 'boolean',
				default: false,
				description: 'Whether to return only my tickets',
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified client',
			},
			{
				displayName: 'Client IDs',
				name: 'client_ids',
				type: 'string',
				default: '',
				description: 'Returns tickets based on client IDs in the array (comma-separated)',
			},
			{
				displayName: 'Client Ref',
				name: 'client_ref',
				type: 'string',
				default: '',
				description: 'Filter by client reference',
			},
			{
				displayName: 'Closed Only',
				name: 'closed_only',
				type: 'boolean',
				default: false,
				description: 'Whether to return only closed tickets',
			},
			{
				displayName: 'Columns ID',
				name: 'columns_id',
				type: 'number',
				default: 0,
				description: 'The column profile ID',
			},
			{
				displayName: 'Contract ID',
				name: 'contract_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified contract',
			},
			{
				displayName: 'Contract Period',
				name: 'contract_period',
				type: 'number',
				default: 0,
				description: 'Filter by the specified contract period',
			},
			{
				displayName: 'Date Search Field',
				name: 'datesearch',
				type: 'options',
			options: [
				{
					name: '-- Select Date Field --',
					value: '',
					description: 'Choose a date field to filter by (required when using Start/End Date)',
				},
				{
					name: 'Audit Date',
					value: 'auditdate',
					description: 'Date when the ticket was audited',
				},
				{
					name: 'Date Created',
					value: 'datecreated',
					description: 'When the ticket was created in the system',
				},
				{
					name: 'Date Occurred',
					value: 'dateoccurred',
					description: 'When the ticket was originally reported/occurred',
				},
				{
					name: 'Deadline Date',
					value: 'deadlinedate',
					description: 'Final deadline date for the ticket',
				},
				{
					name: 'Fix By Date',
					value: 'fixbydate',
					description: 'SLA fix/resolution deadline',
				},
				{
					name: 'Last Action Date',
					value: 'lastactiondate',
					description: 'Date of the last action/update on the ticket',
				},
				{
					name: 'Last Update',
					value: 'last_update',
					description: 'Date of the last modification to the ticket',
				},
				{
					name: 'Respond By Date',
					value: 'respondbydate',
					description: 'SLA response deadline',
				},
				{
					name: 'SLA Action Date',
					value: 'slaactiondate',
					description: 'SLA-related action date',
				},
				{
					name: 'Target Date',
					value: 'targetdate',
					description: 'Target completion date for the ticket',
				},
			],
				default: '',
				description: 'REQUIRED when using Start Date or End Date - Select which date field to search against',
			},
			{
				displayName: 'Debug',
				name: 'debug',
				type: 'boolean',
				default: false,
				description: 'Whether to enable debug mode',
			},
			{
				displayName: 'Default Columns',
				name: 'default_columns',
				type: 'boolean',
				default: false,
				description: 'Whether to include only the default columns in the response',
			},
			{
				displayName: 'Deleted',
				name: 'deleted',
				type: 'boolean',
				default: false,
				description: 'Whether to include deleted tickets',
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: '',
				description: 'Filter on ticket areas - "reqs", "opps", "prjs"',
			},
			{
				displayName: 'End Date',
				name: 'enddate',
				type: 'dateTime',
				default: '',
				description: 'For use with the datesearch parameter',
			},
			{
				displayName: 'End Date Time',
				name: 'enddatetime',
				type: 'boolean',
				default: false,
				description: 'Whether to include project end date and time details in the response',
			},
			{
				displayName: 'Exclude SLA Calcs',
				name: 'excludeslacalcs',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude SLA calculation details in the response',
			},
			{
				displayName: 'Exclude These',
				name: 'excludethese',
				type: 'string',
				default: '',
				description: 'Returns tickets excluding these fault IDs (comma-separated)',
			},
			{
				displayName: 'Exclude Ticket Type Allow All',
				name: 'excludetickettypeallowall',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude ticket type allow all details in the response',
			},
			{
				displayName: 'Extra Portal Filter',
				name: 'extraportalfilter',
				type: 'string',
				default: '',
				description: 'Filter on extraportalfilter field - "MyTicketsOnly", "MyClientTickets"',
			},
			{
				displayName: 'Facebook ID',
				name: 'facebook_id',
				type: 'string',
				default: '',
				description: 'Filter by the specified Facebook ID',
			},
			{
				displayName: 'Fetch Grand Children',
				name: 'fetchgrandchildren',
				type: 'boolean',
				default: false,
				description: 'Whether to fetch grand children tickets',
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'string',
				default: '',
				description: 'Returns tickets based on flagged ticket IDs (comma-separated)',
			},
			{
				displayName: 'Followed and Agents',
				name: 'followedandagents',
				type: 'string',
				default: '',
				description: 'Returns tickets based on agent and follower IDs (comma-separated)',
			},
			{
				displayName: 'Ignore Milestone Restriction',
				name: 'ignoremilestonerestriction',
				type: 'boolean',
				default: false,
				description: 'Whether to ignore milestone restrictions',
			},
			{
				displayName: 'Include Account Manager',
				name: 'includeaccountmanager',
				type: 'boolean',
				default: false,
				description: 'Whether to include account manager details in the response',
			},
			{
				displayName: 'Include Agent',
				name: 'includeagent',
				type: 'boolean',
				default: false,
				description: 'Whether to include agent details in the response',
			},
			{
				displayName: 'Include All Open',
				name: 'includeallopen',
				type: 'boolean',
				default: false,
				description: 'Whether to include all open tickets',
			},
			{
				displayName: 'Include Appointment ID',
				name: 'includeappointmentid',
				type: 'boolean',
				default: false,
				description: 'Whether to include appointment ID in the response',
			},
			{
				displayName: 'Include Approval',
				name: 'includeapproval',
				type: 'string',
				default: '',
				description: 'Filter on approval tickets (1 = approval, 0 = not approval)',
			},
			{
				displayName: 'Include Asset Key Field',
				name: 'includeassetkeyfield',
				type: 'boolean',
				default: false,
				description: 'Whether to include asset key field in the response',
			},
			{
				displayName: 'Include Asset Type',
				name: 'includeassettype',
				type: 'boolean',
				default: false,
				description: 'Whether to include asset type details in the response',
			},
			{
				displayName: 'Include Branch',
				name: 'invlucebranch',
				type: 'boolean',
				default: false,
				description: 'Whether to include branch information in the response',
			},
			{
				displayName: 'Include Breached',
				name: 'includebreached',
				type: 'string',
				default: '',
				description: 'Returns tickets based on breached ticket IDs (comma-separated)',
			},
			{
				displayName: 'Include Budget Type',
				name: 'includebudgettype',
				type: 'boolean',
				default: false,
				description: 'Whether to include budget type details in the response',
			},
			{
				displayName: 'Include Child IDs',
				name: 'includechildids',
				type: 'boolean',
				default: false,
				description: 'Whether to include child ticket IDs in the response',
			},
			{
				displayName: 'Include Child Read',
				name: 'includechildread',
				type: 'boolean',
				default: false,
				description: 'Whether to include child tickets that have been read details in the response',
			},
			{
				displayName: 'Include Children',
				name: 'includechildren',
				type: 'string',
				default: '',
				description: 'Filter on child tickets (0 = no children/not child, 1 = has children, 2 = is child)',
			},
			{
				displayName: 'Include Closed',
				name: 'includeclosed',
				type: 'string',
				default: '',
				description: 'Filter on closed tickets (1 = closed, 0 = not closed)',
			},
			{
				displayName: 'Include Columns',
				name: 'includecolumns',
				type: 'boolean',
				default: false,
				description: 'Whether to include column details in the response',
			},
			{
				displayName: 'Include Completed',
				name: 'includecompleted',
				type: 'boolean',
				default: false,
				description: 'Whether to include completed tickets',
			},
			{
				displayName: 'Include Contract',
				name: 'includecontract',
				type: 'boolean',
				default: false,
				description: 'Whether to include contract details in the response',
			},
			{
				displayName: 'Include Country Region',
				name: 'includecountryregion',
				type: 'boolean',
				default: false,
				description: 'Whether to include country/region details in the response',
			},
			{
				displayName: 'Include Custom Fields',
				name: 'include_custom_fields',
				type: 'multiOptions',
				typeOptions: {
					loadOptionsMethod: 'getCustomFields',
				},
				default: [],
				description: 'Custom Field IDs to include in the response. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Include First Name',
				name: 'includefirstname',
				type: 'boolean',
				default: false,
				description: 'Whether to include first name of user details in the response',
			},
			{
				displayName: 'Include Followed Only',
				name: 'includefollowedonly',
				type: 'string',
				default: '',
				description: 'Returns tickets based on follower IDs (comma-separated)',
			},
			{
				displayName: 'Include Hold',
				name: 'includehold',
				type: 'string',
				default: '',
				description: 'Returns tickets based on on-hold ticket IDs (comma-separated)',
			},
			{
				displayName: 'Include Inactive Techs',
				name: 'includeinactivetechs',
				type: 'string',
				default: '',
				description: 'Returns tickets based on inactive tech IDs (comma-separated)',
			},
			{
				displayName: 'Include Inactive Users',
				name: 'includeinactiveusers',
				type: 'string',
				default: '',
				description: 'Filter on inactive users (1 = inactive, 0 = active)',
			},
			{
				displayName: 'Include ITIL Name',
				name: 'includeitilname',
				type: 'boolean',
				default: false,
				description: 'Whether to include ITIL name details in the response',
			},
			{
				displayName: 'Include Last Action',
				name: 'includelastaction',
				type: 'boolean',
				default: false,
				description: 'Whether to include the last action in the response (single ticket only)',
			},
			{
				displayName: 'Include Last Incoming Email',
				name: 'includelastincomingemail',
				type: 'boolean',
				default: false,
				description: 'Whether to include last incoming email details in the response',
			},
			{
				displayName: 'Include Last Name',
				name: 'includelastname',
				type: 'boolean',
				default: false,
				description: 'Whether to include last name of user details in the response',
			},
			{
				displayName: 'Include Last Note',
				name: 'includelastnote',
				type: 'boolean',
				default: false,
				description: 'Whether to include last note details in the response',
			},
			{
				displayName: 'Include Locked',
				name: 'includelocked',
				type: 'boolean',
				default: false,
				description: 'Whether to include locked tickets',
			},
			{
				displayName: 'Include Mail ID',
				name: 'includemailid',
				type: 'boolean',
				default: false,
				description: 'Whether to include mail ID in the response',
			},
			{
				displayName: 'Include Mailbox',
				name: 'includemailbox',
				type: 'boolean',
				default: false,
				description: 'Whether to include email box details in the response',
			},
			{
				displayName: 'Include My User Only',
				name: 'includemyuseronly',
				type: 'string',
				default: '',
				description: 'Returns tickets based on my user ID (comma-separated)',
			},
			{
				displayName: 'Include Next Activity Date',
				name: 'includenextactivitydate',
				type: 'boolean',
				default: false,
				description: 'Whether to include nextactivitydate in the response',
			},
			{
				displayName: 'Include Next Appointment Type',
				name: 'includenextappointmenttype',
				type: 'boolean',
				default: false,
				description: 'Whether to include next appointment type details in the response',
			},
			{
				displayName: 'Include Open Child Count',
				name: 'inlcludeopenchildcount',
				type: 'boolean',
				default: false,
				description: 'Whether to include open child ticket count in the response',
			},
			{
				displayName: 'Include Parent Subject',
				name: 'includeparentsubject',
				type: 'boolean',
				default: false,
				description: 'Whether to include parent subject in the response',
			},
			{
				displayName: 'Include Projects',
				name: 'includeprojects',
				type: 'string',
				default: '',
				description: 'Filter on projects (1 = Opportunities not Projects, 2 = Projects not Opportunities, 0 = Neither)',
			},
			{
				displayName: 'Include Read',
				name: 'includeread',
				type: 'string',
				default: '',
				description: 'Returns tickets based on read ticket IDs (comma-separated)',
			},
			{
				displayName: 'Include Related Services',
				name: 'includerelatedservices',
				type: 'boolean',
				default: false,
				description: 'Whether to include related services in the response',
			},
			{
				displayName: 'Include Release 1',
				name: 'includerelease1',
				type: 'boolean',
				default: false,
				description: 'Whether to include release 1 details in the response',
			},
			{
				displayName: 'Include Release 2',
				name: 'includerelease2',
				type: 'boolean',
				default: false,
				description: 'Whether to include release 2 details in the response',
			},
			{
				displayName: 'Include Release 3',
				name: 'includerelease3',
				type: 'boolean',
				default: false,
				description: 'Whether to include release 3 details in the response',
			},
			{
				displayName: 'Include Service Category',
				name: 'includeservicecategory',
				type: 'boolean',
				default: false,
				description: 'Whether to include service category in the response',
			},
			{
				displayName: 'Include SLA Action Date',
				name: 'includeslaactiondate',
				type: 'boolean',
				default: false,
				description: 'Whether to include the SLA action date in the response',
			},
			{
				displayName: 'Include SLA Timer',
				name: 'includeslatimer',
				type: 'boolean',
				default: false,
				description: 'Whether to include SLA timer in the response',
			},
			{
				displayName: 'Include Status',
				name: 'includestatus',
				type: 'boolean',
				default: false,
				description: 'Whether to include status details in the response',
			},
			{
				displayName: 'Include Submitted Only',
				name: 'includesubmittedonly',
				type: 'string',
				default: '',
				description: 'Returns tickets based on agent submitted IDs (comma-separated)',
			},
			{
				displayName: 'Include Supplier',
				name: 'includesupplier',
				type: 'boolean',
				default: false,
				description: 'Whether to include supplier details in the response',
			},
			{
				displayName: 'Include Ticket Type',
				name: 'includetickettype',
				type: 'boolean',
				default: false,
				description: 'Whether to include ticket type details in the response',
			},
			{
				displayName: 'Include Time Taken',
				name: 'includetimetaken',
				type: 'boolean',
				default: false,
				description: 'Whether to include time taken in the response',
			},
			{
				displayName: 'Include Top Level',
				name: 'includetoplevel',
				type: 'boolean',
				default: false,
				description: 'Whether to include top level details in the response',
			},
			{
				displayName: 'Include User Departments',
				name: 'includuserdepartments',
				type: 'boolean',
				default: false,
				description: 'Whether to include user departments in the response',
			},
			{
				displayName: 'Include Viewing',
				name: 'includeviewing',
				type: 'boolean',
				default: false,
				description: 'Whether to include tickets currently being viewed details in the response',
			},
			{
				displayName: 'Include Workflow Stage',
				name: 'includeworkflowstage',
				type: 'boolean',
				default: false,
				description: 'Whether to include workflow stage details in the response',
			},
			{
				displayName: 'Include Workflow Stage Number',
				name: 'includeworkflowstagenumber',
				type: 'boolean',
				default: false,
				description: 'Whether to include workflow stage number in the response',
			},
			{
				displayName: 'Is Milestone',
				name: 'ismilestone',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by milestone tickets',
			},
			{
				displayName: 'Is Orion',
				name: 'isorion',
				type: 'boolean',
				default: false,
				description: 'Whether to include integration orion details in the response',
			},
			{
				displayName: 'Is Quick Time Search',
				name: 'isquicktimesearch',
				type: 'boolean',
				default: false,
				description: 'Whether to return only quick time tickets in the response',
			},
			{
				displayName: 'Is SCOM',
				name: 'isscom',
				type: 'boolean',
				default: false,
				description: 'Whether to include integration SCOM details in the response',
			},
			{
				displayName: 'Is Teams',
				name: 'isteams',
				type: 'boolean',
				default: false,
				description: 'Whether to return only teams tickets in the response',
			},
			{
				displayName: 'Is Zapier',
				name: 'iszapier',
				type: 'boolean',
				default: false,
				description: 'Whether to return a single ticket based on permissions in the response',
			},
			{
				displayName: 'ITIL Request Type',
				name: 'itil_requesttype',
				type: 'string',
				default: '',
				description: 'Returns tickets based on ITIL request type IDs (comma-separated)',
			},
			{
				displayName: 'ITIL Request Type ID',
				name: 'itil_requesttype_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified ITIL ticket type',
			},
			{
				displayName: 'Kanban View On Agent App',
				name: 'kanbanviewontheagentapp',
				type: 'boolean',
				default: false,
				description: 'Whether to include agent app kanban view in the response',
			},
			{
				displayName: 'Kanban View On Portal',
				name: 'kanbanviewontheportal',
				type: 'boolean',
				default: false,
				description: 'Whether to include portal kanban view in the response',
			},
			{
				displayName: 'Last Update From Date',
				name: 'lastupdatefromdate',
				type: 'boolean',
				default: false,
				description: 'Whether to filter from last update date',
			},
			{
				displayName: 'Last Update To Date',
				name: 'lastupdatetodate',
				type: 'boolean',
				default: false,
				description: 'Whether to filter to last update date',
			},
			{
				displayName: 'List ID',
				name: 'list_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified list',
			},
			{
				displayName: 'Milestone ID',
				name: 'milestone_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified milestone',
			},
			{
				displayName: 'Mine',
				name: 'mine',
				type: 'boolean',
				default: false,
				description: 'Whether to include only the tickets that belong to yourself in the response',
			},
			{
				displayName: 'No Charge Only',
				name: 'nochargeonly',
				type: 'boolean',
				default: false,
				description: 'Whether to return only no-charge tickets',
			},
			{
				displayName: 'No Time',
				name: 'notime',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude time information',
			},
			{
				displayName: 'Only Time',
				name: 'onlytime',
				type: 'boolean',
				default: false,
				description: 'Whether to return only time information',
			},
			{
				displayName: 'Open Only',
				name: 'open_only',
				type: 'boolean',
				default: false,
				description: 'Whether to return only open tickets',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'string',
				default: '',
				description: 'The name of the field to order by first',
			},
			{
				displayName: 'Order 2',
				name: 'order2',
				type: 'string',
				default: '',
				description: 'The name of the field to order by second',
			},
			{
				displayName: 'Order 3',
				name: 'order3',
				type: 'string',
				default: '',
				description: 'The name of the field to order by third',
			},
			{
				displayName: 'Order 4',
				name: 'order4',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fourth',
			},
			{
				displayName: 'Order 5',
				name: 'order5',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fifth',
			},
			{
				displayName: 'Order Desc',
				name: 'orderdesc',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on first order',
			},
			{
				displayName: 'Order Desc 2',
				name: 'orderdesc2',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on second order',
			},
			{
				displayName: 'Order Desc 3',
				name: 'orderdesc3',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on third order',
			},
			{
				displayName: 'Order Desc 4',
				name: 'orderdesc4',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fourth order',
			},
			{
				displayName: 'Order Desc 5',
				name: 'orderdesc5',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fifth order',
			},
			{
				displayName: 'Orion Type',
				name: 'orion_type',
				type: 'number',
				default: 0,
				description: 'Filter by the orion type',
			},
			{
				displayName: 'Page Number',
				name: 'page_no',
				type: 'number',
				default: 0,
				description: 'When using pagination, the page number to return',
			},
			{
				displayName: 'Page Size',
				name: 'page_size',
				type: 'number',
				default: 0,
				typeOptions: {
					maxValue: 100,
				},
				description: 'When using pagination, the size of the page (max: 100)',
			},
			{
				displayName: 'Paginate',
				name: 'pageinate',
				type: 'boolean',
				default: false,
				description: 'Whether to use pagination in the response',
			},
			{
				displayName: 'Parent ID',
				name: 'parent_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified parent',
			},
			{
				displayName: 'Pending Review',
				name: 'pending_review',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on pending review',
			},
			{
				displayName: 'Per Action',
				name: 'per_action',
				type: 'boolean',
				default: false,
				description: 'Whether to calculate billing per action',
			},
			{
				displayName: 'Prepay or Contract Only',
				name: 'prepayorcontractonly',
				type: 'boolean',
				default: false,
				description: 'Whether to return only prepaid or contract tickets',
			},
			{
				displayName: 'Priority',
				name: 'priority',
				type: 'string',
				default: '',
				description: 'Returns tickets based on priority IDs (comma-separated)',
			},
			{
				displayName: 'Product',
				name: 'product',
				type: 'string',
				default: '',
				description: 'Returns tickets based on product IDs (comma-separated)',
			},
			{
				displayName: 'Project IDs',
				name: 'project_ids',
				type: 'string',
				default: '',
				description: 'Filter by project IDs (comma-separated)',
			},
			{
				displayName: 'Ready for Invoicing',
				name: 'ready_for_invoicing',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on ready for invoicing',
			},
			{
				displayName: 'Related ID',
				name: 'related_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified related ticket',
			},
			{
				displayName: 'Release ID',
				name: 'release_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified release',
			},
			{
				displayName: 'Request Type Group',
				name: 'requesttypegroup',
				type: 'string',
				default: '',
				description: 'Returns tickets based on request type group IDs (comma-separated)',
			},
			{
				displayName: 'Request Type ID',
				name: 'requesttype_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified request type',
			},
			{
				displayName: 'Request Type Names or IDs',
				name: 'requesttype',
				type: 'multiOptions',
				default: [],
				description: 'Select ticket types to filter by. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
				typeOptions: {
					loadOptionsMethod: 'getTicketTypes',
				},
				options: [],
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filter response based on the search string',
			},
			{
				displayName: 'Search Actions',
				name: 'searchactions',
				type: 'boolean',
				default: false,
				description: 'Whether to search actions when using search',
			},
			{
				displayName: 'Search Details',
				name: 'search_details',
				type: 'string',
				default: '',
				description: 'Returns tickets based on the details matching the search',
			},
			{
				displayName: 'Search ID',
				name: 'search_id',
				type: 'string',
				default: '',
				description: 'Returns tickets based on IDs matching the search',
			},
			{
				displayName: 'Search Inventory Number',
				name: 'search_inventory_number',
				type: 'string',
				default: '',
				description: 'Returns tickets based on an asset tag matching the search',
			},
			{
				displayName: 'Search Opp Company Name',
				name: 'search_oppcompanyname',
				type: 'string',
				default: '',
				description: 'Returns tickets based on opportunity company name matching the search',
			},
			{
				displayName: 'Search Opp Contact Name',
				name: 'search_oppcontactname',
				type: 'string',
				default: '',
				description: 'Returns tickets based on opportunity contact name matching the search',
			},
			{
				displayName: 'Search Opp Email Address',
				name: 'search_oppemailaddress',
				type: 'string',
				default: '',
				description: 'Returns tickets based on opportunity email address matching the search',
			},
			{
				displayName: 'Search Release 1',
				name: 'search_release1',
				type: 'string',
				default: '',
				description: 'Returns tickets based on release 1 matching the search',
			},
			{
				displayName: 'Search Release 2',
				name: 'search_release2',
				type: 'string',
				default: '',
				description: 'Returns tickets based on release 2 matching the search',
			},
			{
				displayName: 'Search Release 3',
				name: 'search_release3',
				type: 'string',
				default: '',
				description: 'Returns tickets based on release 3 matching the search',
			},
			{
				displayName: 'Search Release Note',
				name: 'search_releasenote',
				type: 'string',
				default: '',
				description: 'Returns tickets based on the release note matching the search',
			},
			{
				displayName: 'Search Reported By',
				name: 'search_reportedby',
				type: 'string',
				default: '',
				description: 'Returns tickets based on the reportedby field matching the search',
			},
			{
				displayName: 'Search Summary',
				name: 'search_summary',
				type: 'string',
				default: '',
				description: 'Returns tickets based on the summary matching the search',
			},
			{
				displayName: 'Search Supplier Reference',
				name: 'search_supplier_reference',
				type: 'string',
				default: '',
				description: 'Returns tickets based on the supplier reference matching the search',
			},
			{
				displayName: 'Search This Ticket ID',
				name: 'searchthisticketid',
				type: 'number',
				default: 0,
				description: 'Filter by the specified ticket',
			},
			{
				displayName: 'Search User Name',
				name: 'search_user_name',
				type: 'string',
				default: '',
				description: 'Returns tickets based on users matching the search',
			},
			{
				displayName: 'Search Version',
				name: 'search_version',
				type: 'string',
				default: '',
				description: 'Returns tickets based on the software version matching the search',
			},
			{
				displayName: 'Service ID',
				name: 'service_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified service',
			},
			{
				displayName: 'Show on Roadmap',
				name: 'showonroadmap',
				type: 'string',
				default: '',
				description: 'Filter on roadmap visibility (1 = visible, 0 = not visible)',
			},
			{
				displayName: 'Site ID',
				name: 'site_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified site',
			},
			{
				displayName: 'Site Postcode',
				name: 'sitepostcode',
				type: 'boolean',
				default: false,
				description: 'Whether to include site postcode details in the response',
			},
			{
				displayName: 'SLA',
				name: 'sla',
				type: 'string',
				default: '',
				description: 'Returns tickets based on SLA IDs (comma-separated)',
			},
			{
				displayName: 'Sprint for Ticket Type ID',
				name: 'sprint_for_tickettype_id',
				type: 'number',
				default: 0,
				description: 'Filter by sprint for specific ticket type',
			},
			{
				displayName: 'Sprints',
				name: 'sprints',
				type: 'boolean',
				default: false,
				description: 'Whether to return only sprint tickets in the response',
			},
			{
				displayName: 'Start and End Set',
				name: 'startandendset',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on tickets that have a project start and end date set',
			},
			{
				displayName: 'Start Date',
				name: 'startdate',
				type: 'dateTime',
				default: '',
				description: 'For use with the datesearch parameter',
			},
			{
				displayName: 'Start Date Time',
				name: 'startdatetime',
				type: 'boolean',
				default: false,
				description: 'Whether to include project start date and time details in the response',
			},
			{
				displayName: 'Status ID',
				name: 'status_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified status',
			},
			{
				displayName: 'Status Names or IDs',
				name: 'status',
				type: 'multiOptions',
				default: [],
				description: 'Select ticket statuses to filter by. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
				typeOptions: {
					loadOptionsMethod: 'getTicketStatuses',
				},
				options: [],
			},
			{
				displayName: 'Submitted and Agents',
				name: 'submittedandagents',
				type: 'string',
				default: '',
				description: 'Returns tickets based on agent and agent submitted IDs (comma-separated)',
			},
			{
				displayName: 'Supplier ID',
				name: 'supplier_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified supplier',
			},
			{
				displayName: 'Supplier Status',
				name: 'supplier_status',
				type: 'string',
				default: '',
				description: 'Returns tickets based on supplier status IDs (comma-separated)',
			},
			{
				displayName: 'Team',
				name: 'team',
				type: 'string',
				default: '',
				description: 'Returns tickets based on Team IDs (comma-separated)',
			},
			{
				displayName: 'Team Name',
				name: 'team_name',
				type: 'string',
				default: '',
				description: 'Include team name details in the response',
			},
			{
				displayName: 'Third Party ID',
				name: 'third_party_id',
				type: 'number',
				default: 0,
				description: 'Returns tickets based on the Third Party ID',
			},
			{
				displayName: 'Third Party ID String',
				name: 'third_party_id_string',
				type: 'string',
				default: '',
				description: 'Returns tickets based on the Third Party ID String',
			},
			{
				displayName: 'Ticket Area ID',
				name: 'ticketarea_id',
				type: 'number',
				default: 0,
				description: 'Will return tickets in this ticket area in the response',
			},
			{
				displayName: 'Ticket Contract ID',
				name: 'ticketcontract_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified ticket contract',
			},
			{
				displayName: 'Ticket ID Only',
				name: 'ticketidonly',
				type: 'boolean',
				default: false,
				description: 'Whether to return only the ID fields of the tickets (not compatible with pagination)',
			},
			{
				displayName: 'Ticket IDs',
				name: 'ticketids',
				type: 'string',
				default: '',
				description: 'Returns only the tickets specified in the response (comma-separated)',
			},
			{
				displayName: 'Ticket Link Type',
				name: 'ticketlinktype',
				type: 'number',
				default: 0,
				description: 'Filter by ticket link type',
			},
			{
				displayName: 'Top Level ID',
				name: 'toplevel_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified top level',
			},
			{
				displayName: 'Unlinked Only',
				name: 'unlinked_only',
				type: 'boolean',
				default: false,
				description: 'Whether to return only unlinked tickets in the response',
			},
			{
				displayName: 'User ID',
				name: 'user_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified user',
			},
			{
				displayName: 'Username',
				name: 'username',
				type: 'string',
				default: '',
				description: 'Filter by the specified username',
			},
			{
				displayName: 'UTC Offset',
				name: 'utcoffset',
				type: 'number',
				default: 0,
				typeOptions: {
					numberPrecision: 2,
				},
				description: 'Adds an offset to the UTC date',
			},
			{
				displayName: 'View ID',
				name: 'view_id',
				type: 'number',
				default: 0,
				description: 'The ID of the filter profile to filter by',
			},
			{
				displayName: 'With Attachments',
				name: 'withattachments',
				type: 'boolean',
				default: false,
				description: 'Whether to return only tickets with 1 or more attachment',
			},
		],
	},
];