import { INodeProperties } from 'n8n-workflow';
import { filtersJsonProperty } from '../../../filterParameters';

export const description: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['actions'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['actions'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['actions'],
				operation: ['getAll'],
			},
		},
	options: [
		{
			displayName: 'Action Outcome',
			name: 'actoutcome',
			type: 'string',
			default: '',
			description: 'Filter on the name of the action',
		},
		{
			displayName: 'Action Outcome Number',
			name: 'actoutcomenum',
			type: 'number',
			default: 0,
			description: 'Filter on the system field ID',
		},
		{
			displayName: 'Agent Only',
			name: 'agentonly',
			type: 'boolean',
			default: false,
			description: 'Whether to get actions done by Agents only',
		},
		{
			displayName: 'Conversation Only',
			name: 'conversationonly',
			type: 'boolean',
			default: false,
			description: 'Whether to get actions relating to the Agent to End User conversation only',
		},
		{
			displayName: 'Date Search Field',
			name: 'datesearch',
			type: 'string',
			default: '',
			description: 'Date search field parameter',
		},
		{
			displayName: 'End Date',
			name: 'enddate',
			type: 'dateTime',
			default: '',
			description: 'Specifies the search parameter in which actions will have occurred before this date',
		},
		{
			displayName: 'Exclude Billing',
			name: 'excludebilling',
			type: 'boolean',
			default: false,
			description: 'Whether to exclude any actions associated with billing (e.g. Send Invoice by Email)',
		},
		{
			displayName: 'Exclude Hidden From Internal IT',
			name: 'excludehiddenfrominternalit',
			type: 'boolean',
			default: false,
			description: 'Whether to exclude any action marked at action level to be hidden from Agents with Client Group set',
		},
		{
			displayName: 'Exclude Private',
			name: 'excludeprivate',
			type: 'boolean',
			default: false,
			description: 'Whether to get public actions only',
		},
		{
			displayName: 'Exclude System',
			name: 'excludesys',
			type: 'boolean',
			default: false,
			description: 'Whether to exclude system actions',
		},
		{
			displayName: 'Important Only',
			name: 'importantonly',
			type: 'boolean',
			default: false,
			description: 'Whether to get important actions only',
		},
		{
			displayName: 'Important Top',
			name: 'importanttop',
			type: 'boolean',
			default: false,
			description: 'Whether to order the response by important actions first',
		},
		{
			displayName: 'Include Agent Details',
			name: 'includeagentdetails',
			type: 'boolean',
			default: false,
			description: 'Whether to include agent details in the response',
		},
		{
			displayName: 'Include Attachments',
			name: 'includeattachments',
			type: 'boolean',
			default: false,
			description: 'Whether to include attachment details in the response',
		},
		{
			displayName: 'Include Facebook Fields',
			name: 'includefacebookfields',
			type: 'boolean',
			default: false,
			description: 'Whether to include Facebook fields in the response',
		},
		{
			displayName: 'Include HTML Email',
			name: 'includehtmlemail',
			type: 'boolean',
			default: false,
			description: 'Whether to include the action email HTML as part of the response',
		},
		{
			displayName: 'Include HTML Note',
			name: 'includehtmlnote',
			type: 'boolean',
			default: false,
			description: 'Whether to include the action note HTML as part of the response',
		},
		{
			displayName: 'Include Non-Action Attachments',
			name: 'includenonactionattachments',
			type: 'boolean',
			default: false,
			description: 'Whether to include non-action attachments in the response',
		},
		{
			displayName: 'Include Translations',
			name: 'includetranslations',
			type: 'boolean',
			default: false,
			description: 'Whether to include the translation count in the response',
		},
		{
			displayName: 'Include Twitter Fields',
			name: 'includetwitterfields',
			type: 'boolean',
			default: false,
			description: 'Whether to include Twitter fields in the response',
		},
		{
			displayName: 'Intra-Ticket Only',
			name: 'intraticketonly',
			type: 'boolean',
			default: false,
			description: 'Whether to get actions that are part of the intra-ticket conversation',
		},
		{
			displayName: 'Is Child Notes',
			name: 'ischildnotes',
			type: 'boolean',
			default: false,
			description: 'Whether to get actions from child tickets only',
		},
		{
			displayName: 'Is Related Notes',
			name: 'isrelatednotes',
			type: 'boolean',
			default: false,
			description: 'Whether to get actions from related tickets only',
		},
		{
			displayName: 'SLA Only',
			name: 'slaonly',
			type: 'boolean',
			default: false,
			description: 'Whether to get SLA hold and release actions only',
		},
		{
			displayName: 'Start Date',
			name: 'startdate',
			type: 'dateTime',
			default: '',
			description: 'Specifies the search parameter in which actions will have occurred after this date',
		},
		{
			displayName: 'Supplier Only',
			name: 'supplieronly',
			type: 'boolean',
			default: false,
			description: 'Whether to get actions relating to Suppliers only',
		},
		{
			displayName: 'Ticket ID',
			name: 'ticket_id',
			type: 'number',
			default: 0,
			description: 'The ID of the Ticket to get actions for',
		},
		{
			displayName: 'Time Entries Only',
			name: 'timeentriesonly',
			type: 'boolean',
			default: false,
			description: 'Whether to get time entries only',
		},
	],
	},
	filtersJsonProperty('actions'),
];
