import { INodeProperties } from 'n8n-workflow';

export const createDescription: INodeProperties[] = [
	// Core required fields
	{
		displayName: 'Summary',
		name: 'summary',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'The ticket summary/subject',
	},
	
	// Core optional fields
	{
		displayName: 'Details',
		name: 'details',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['create'],
			},
		},
		typeOptions: {
			rows: 4,
		},
		default: '',
		description: 'The ticket details/description',
	},
	{
		displayName: 'Client ID',
		name: 'client_id',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['create'],
			},
		},
		default: 0,
	},
	{
		displayName: 'Site ID',
		name: 'site_id',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['create'],
			},
		},
		default: 0,
	},
	{
		displayName: 'User ID',
		name: 'user_id',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['create'],
			},
		},
		default: 0,
	},
	
	// Additional fields collection
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['tickets'],
				operation: ['create'],
			},
		},
	options: [
			{
				displayName: 'Address Line 1',
				name: 'oppaddr1',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Address Line 2',
				name: 'oppaddr2',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Agent ID',
				name: 'agent_id',
				type: 'number',
				default: 0,
				description: 'The assigned agent ID',
			},
			{
				displayName: 'Billable',
				name: 'isbillable',
				type: 'boolean',
				default: true,
				description: 'Whether the ticket is billable',
			},
			{
				displayName: 'Category 1',
				name: 'category_1',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Category 2',
				name: 'category_2',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Category 3',
				name: 'category_3',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Category 4',
				name: 'category_4',
				type: 'string',
				default: '',
			},
			{
				displayName: 'City',
				name: 'oppaddr3',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Company Name',
				name: 'oppcompanyname',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Contact Name',
				name: 'oppcontactname',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Cost',
				name: 'cost',
				type: 'number',
				default: 0,
				description: 'Cost amount',
			},
			{
				displayName: 'Custom Field 1',
				name: 'userdef1',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Custom Field 2',
				name: 'userdef2',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Custom Field 3',
				name: 'userdef3',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Custom Field 4',
				name: 'userdef4',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Custom Field 5',
				name: 'userdef5',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Date Occurred',
				name: 'dateoccurred',
				type: 'dateTime',
				default: '',
				description: 'When the issue occurred',
			},
			{
				displayName: 'Deadline Date',
				name: 'deadlinedate',
				type: 'dateTime',
				default: '',
			},
			{
				displayName: 'Email Address',
				name: 'oppemailaddress',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Email CC List',
				name: 'emailcclist',
				type: 'string',
				default: '',
				description: 'Email addresses to CC',
			},
			{
				displayName: 'Email To List',
				name: 'emailtolist',
				type: 'string',
				default: '',
				description: 'Email addresses to notify',
			},
			{
				displayName: 'Estimate (Hours)',
				name: 'estimate',
				type: 'number',
				default: 0,
				description: 'Estimated time in hours',
			},
			{
				displayName: 'Exclude From SLA',
				name: 'excludefromsla',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude from SLA calculations',
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'boolean',
				default: false,
				description: 'Whether the ticket is flagged',
			},
			{
				displayName: 'Impact',
				name: 'impact',
				type: 'options',
				options: [
					{ name: 'None', value: 0 },
					{ name: 'Low', value: 1 },
					{ name: 'Medium', value: 2 },
					{ name: 'High', value: 3 },
				],
				default: 0,
				description: 'Impact level',
			},
			{
				displayName: 'Important Contact',
				name: 'isimportantcontact',
				type: 'boolean',
				default: false,
				description: 'Whether this is from an important contact',
			},
			{
				displayName: 'Is VIP',
				name: 'is_vip',
				type: 'boolean',
				default: false,
				description: 'Whether this is a VIP ticket',
			},
			{
				displayName: 'On Hold',
				name: 'onhold',
				type: 'boolean',
				default: false,
				description: 'Whether the ticket is on hold',
			},
			{
				displayName: 'Phone Number',
				name: 'phonenumber',
				type: 'string',
				default: '',
				description: 'Contact phone number',
			},
			{
				displayName: 'Postal Code',
				name: 'opppostcode',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Priority ID',
				name: 'priority_id',
				type: 'number',
				default: 4,
			},
			{
				displayName: 'Quantity',
				name: 'quantity',
				type: 'number',
				default: 1,
			},
			{
				displayName: 'Reported By',
				name: 'reportedby',
				type: 'string',
				default: '',
				description: 'Who reported the ticket',
			},
			{
				displayName: 'Show for Users',
				name: 'showforusers',
				type: 'boolean',
				default: true,
				description: 'Whether users can see this ticket',
			},
			{
				displayName: 'SLA ID',
				name: 'sla_id',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Source',
				name: 'source',
				type: 'number',
				default: 0,
				description: 'Source of the ticket',
			},
			{
				displayName: 'State/Region',
				name: 'oppaddr4',
				type: 'string',
				default: '',
				description: 'State or region',
			},
			{
				displayName: 'Status ID',
				name: 'status_id',
				type: 'number',
				default: 1,
			},
			{
				displayName: 'Target Date',
				name: 'targetdate',
				type: 'dateTime',
				default: '',
				description: 'Target completion date',
			},
			{
				displayName: 'Team ID',
				name: 'team_id',
				type: 'number',
				default: 0,
				description: 'The assigned team ID',
			},
			{
				displayName: 'Telephone',
				name: 'opptel',
				type: 'string',
				default: '',
				description: 'Telephone number',
			},
			{
				displayName: 'Ticket Tags',
				name: 'ticket_tags',
				type: 'string',
				default: '',
				description: 'Ticket tags (comma-separated)',
			},
			{
				displayName: 'Ticket Type ID',
				name: 'tickettype_id',
				type: 'number',
				default: 1,
			},
			{
				displayName: 'Urgency',
				name: 'urgency',
				type: 'options',
				options: [
					{ name: 'None', value: 0 },
					{ name: 'Low', value: 1 },
					{ name: 'Medium', value: 2 },
					{ name: 'High', value: 3 },
				],
				default: 0,
				description: 'Urgency level',
			},
			{
				displayName: 'User Email',
				name: 'user_email',
				type: 'string',
				default: '',
				description: 'User email address',
			},
		],
	},
];