import { INodeProperties } from 'n8n-workflow';

export const description: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['projects'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['projects'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['projects'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Advanced Search',
				name: 'advanced_search',
				type: 'string',
				default: '',
				description: 'Advanced search string',
			},
			{
				displayName: 'Agent Name or ID',
				name: 'agent_id',
				type: 'options',
				default: '',
				description: 'Filter by the specified agent. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
				typeOptions: {
					loadOptionsMethod: 'getAgents',
				},
				options: [],
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified client',
			},
			{
				displayName: 'Closed Only',
				name: 'closed_only',
				type: 'boolean',
				default: false,
				description: 'Whether to return only closed projects',
			},
			{
				displayName: 'Date Search Field',
				name: 'datesearch',
				type: 'string',
				default: '',
				description: 'Date search field parameter',
			},
			{
				displayName: 'End Date',
				name: 'enddate',
				type: 'dateTime',
				default: '',
				description: 'End date for date range filtering',
			},
			{
				displayName: 'Flagged',
				name: 'flagged',
				type: 'boolean',
				default: false,
				description: 'Whether to return only flagged projects',
			},
			{
				displayName: 'Include Attachments',
				name: 'includeattachments',
				type: 'boolean',
				default: false,
				description: 'Whether to include attachment details in the response',
			},
			{
				displayName: 'Include Custom Fields',
				name: 'includecustomfields',
				type: 'boolean',
				default: false,
				description: 'Whether to include custom fields in the response',
			},
			{
				displayName: 'Include Details',
				name: 'includedetails',
				type: 'boolean',
				default: false,
				description: 'Whether to include extra objects in the response',
			},
			{
				displayName: 'Include Projects',
				name: 'includeprojects',
				type: 'string',
				default: '',
				description: 'Filter on projects (1 = Opportunities not Projects, 2 = Projects not Opportunities, 0 = Neither)',
			},
			{
				displayName: 'Mine',
				name: 'mine',
				type: 'boolean',
				default: false,
				description: 'Whether to include only projects that belong to yourself',
			},
			{
				displayName: 'On Hold',
				name: 'onhold',
				type: 'boolean',
				default: false,
				description: 'Whether to return only projects on hold',
			},
			{
				displayName: 'Open Only',
				name: 'open_only',
				type: 'boolean',
				default: false,
				description: 'Whether to return only open projects',
			},
			{
				displayName: 'Pipeline Stage ID',
				name: 'pipeline_stage_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified pipeline stage',
			},
			{
				displayName: 'Priority ID',
				name: 'priority_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified priority',
			},
			{
				displayName: 'Project Internal Task',
				name: 'projectinternaltask',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by project internal tasks',
			},
			{
				displayName: 'Project Type Name or ID',
				name: 'tickettype_id',
				type: 'options',
				default: '',
				description: 'Filter by the specified project type. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
				typeOptions: {
					loadOptionsMethod: 'getTicketTypes',
				},
				options: [],
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filter response based on the search string',
			},
			{
				displayName: 'Search Details',
				name: 'search_details',
				type: 'string',
				default: '',
				description: 'Returns projects based on the details matching the search',
			},
			{
				displayName: 'Search Summary',
				name: 'search_summary',
				type: 'string',
				default: '',
				description: 'Returns projects based on the summary matching the search',
			},
			{
				displayName: 'Show on Roadmap',
				name: 'showonroadmap',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by projects shown on roadmap',
			},
			{
				displayName: 'Site ID',
				name: 'site_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified site',
			},
			{
				displayName: 'Start Date',
				name: 'startdate',
				type: 'dateTime',
				default: '',
				description: 'Start date for date range filtering',
			},
			{
				displayName: 'Status ID',
				name: 'status_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified status',
			},
			{
				displayName: 'Team ID',
				name: 'team_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified team',
			},
			{
				displayName: 'User ID',
				name: 'user_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified user',
			},
			{
				displayName: 'Workflow ID',
				name: 'workflow_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified workflow',
			},
		],
	},
];