import { INodeProperties } from 'n8n-workflow';

export const updateDescription: INodeProperties[] = [
	{
		displayName: 'User ID',
		name: 'id',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['users'],
				operation: ['update'],
			},
		},
		default: 0,
		required: true,
		description: 'The ID of the user to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['users'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'number',
				default: 0,
				description: 'The client ID to which the user belongs',
			},
			{
				displayName: 'Colour',
				name: 'colour',
				type: 'color',
				default: '',
				description: 'Colour code for the user (e.g., #e83c4a)',
			},
			{
				displayName: 'Email Address',
				name: 'emailaddress',
				type: 'string',
				default: '',
				description: 'The email address for the user',
			},
			{
				displayName: 'First Name',
				name: 'firstname',
				type: 'string',
				default: '',
				description: 'The first name of the user',
			},
			{
				displayName: 'Ignore Automated Billing',
				name: 'ignoreautomatedbilling',
				type: 'boolean',
				default: false,
				description: 'Whether to ignore automated billing for this user',
			},
			{
				displayName: 'Inactive',
				name: 'inactive',
				type: 'boolean',
				default: false,
				description: 'Whether the user is inactive',
			},
			{
				displayName: 'Initials',
				name: 'initials',
				type: 'string',
				default: '',
				description: 'The initials of the user',
			},
			{
				displayName: 'Is Important Contact',
				name: 'isimportantcontact',
				type: 'boolean',
				default: false,
				description: 'Whether this is an important contact',
			},
			{
				displayName: 'Is Important Contact 2',
				name: 'isimportantcontact2',
				type: 'boolean',
				default: false,
				description: 'Whether this is a secondary important contact',
			},
			{
				displayName: 'Is Service Account',
				name: 'isserviceaccount',
				type: 'boolean',
				default: false,
				description: 'Whether this is a service account',
			},
			{
				displayName: 'Linked Agent ID',
				name: 'linked_agent_id',
				type: 'number',
				default: 0,
				description: 'The ID of the linked agent',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'The full name of the user',
			},
			{
				displayName: 'Never Send Emails',
				name: 'neversendemails',
				type: 'boolean',
				default: false,
				description: 'Whether to never send emails to this user',
			},
			{
				displayName: 'Phone Number',
				name: 'phonenumber',
				type: 'string',
				default: '',
				description: 'The phone number of the user',
			},
			{
				displayName: 'Phone Number Preferred',
				name: 'phonenumber_preferred',
				type: 'string',
				default: '',
				description: 'The preferred phone number of the user',
			},
			{
				displayName: 'Priority ID',
				name: 'priority_id',
				type: 'number',
				default: 0,
				description: 'The priority ID for the user',
			},
			{
				displayName: 'Site ID',
				name: 'site_id',
				type: 'number',
				default: 0,
				description: 'The site ID to which the user belongs',
			},
			{
				displayName: 'Site Phone Number',
				name: 'sitephonenumber',
				type: 'string',
				default: '',
				description: 'Phone number associated with the site',
			},
			{
				displayName: 'Surname',
				name: 'surname',
				type: 'string',
				default: '',
				description: 'The surname/last name of the user',
			},
			{
				displayName: 'Tel Pref',
				name: 'telpref',
				type: 'number',
				default: 0,
				description: 'Telephone preference setting',
			},
			{
				displayName: 'WhatsApp Number',
				name: 'whatsapp_number',
				type: 'string',
				default: '',
				description: 'The WhatsApp number of the user',
			},
		],
	},
];