import { INodeProperties } from 'n8n-workflow';

export const updateDescription: INodeProperties[] = [
	{
		displayName: 'Ticket Type ID',
		name: 'ticketTypeId',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['ticketTypes'],
				operation: ['update'],
			},
		},
		default: 0,
		required: true,
		description: 'ID of the ticket type to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['ticketTypes'],
				operation: ['update'],
			},
		},
	options: [
		{
			displayName: 'Agents Can Select',
			name: 'agentscanselect',
			type: 'boolean',
			default: true,
			description: 'Whether agents can select this ticket type',
		},
		{
			displayName: 'Allow All Actions',
			name: 'allowall_actions',
			type: 'boolean',
			default: true,
			description: 'Whether all actions are allowed',
		},
		{
			displayName: 'Allow All Charge Rates',
			name: 'allowall_chargerates',
			type: 'boolean',
			default: true,
			description: 'Whether all charge rates are allowed',
		},
		{
			displayName: 'Allow All Status',
			name: 'allowall_status',
			type: 'boolean',
			default: true,
			description: 'Whether all statuses are allowed',
		},
		{
			displayName: 'Allow All Team',
			name: 'allowall_team',
			type: 'boolean',
			default: true,
			description: 'Whether all teams can use this ticket type',
		},
		{
			displayName: 'Allow Attachments',
			name: 'allowattachments',
			type: 'boolean',
			default: true,
			description: 'Whether attachments are allowed for this ticket type',
		},
		{
			displayName: 'Anonymous Can Select',
			name: 'anonymouscanselect',
			type: 'boolean',
			default: false,
			description: 'Whether anonymous users can select this ticket type',
		},
		{
			displayName: 'Approval Message',
			name: 'approval_message',
			type: 'string',
			default: '',
			description: 'Message to display for approval requests',
		},
		{
			displayName: 'Charge Rate',
			name: 'chargerate',
			type: 'number',
			default: 0,
			description: 'Default charge rate for this ticket type',
		},
		{
			displayName: 'Default Agent',
			name: 'default_agent',
			type: 'number',
			default: 0,
			description: 'Default agent ID for tickets of this type',
		},
		{
			displayName: 'Default Category 1',
			name: 'default_category_1',
			type: 'string',
			default: '',
			description: 'Default category 1 value',
		},
		{
			displayName: 'Default Category 2',
			name: 'default_category_2',
			type: 'string',
			default: '',
			description: 'Default category 2 value',
		},
		{
			displayName: 'Default Category 3',
			name: 'default_category_3',
			type: 'string',
			default: '',
			description: 'Default category 3 value',
		},
		{
			displayName: 'Default Category 4',
			name: 'default_category_4',
			type: 'string',
			default: '',
			description: 'Default category 4 value',
		},
		{
			displayName: 'Default Details',
			name: 'default_details',
			type: 'string',
			default: '',
			description: 'Default details template',
		},
		{
			displayName: 'Default Details HTML',
			name: 'default_details_html',
			type: 'string',
			default: '',
			description: 'Default details HTML template',
		},
		{
			displayName: 'Default Exclude From SLA',
			name: 'default_excludefromsla',
			type: 'boolean',
			default: false,
			description: 'Whether to exclude from SLA by default',
		},
		{
			displayName: 'Default Priority',
			name: 'default_priority',
			type: 'number',
			default: 0,
			description: 'Default priority ID for tickets of this type',
		},
		{
			displayName: 'Default Send ACK',
			name: 'default_sendack',
			type: 'number',
			default: 0,
			description: 'Default send acknowledgment setting',
		},
		{
			displayName: 'Default Send Email',
			name: 'default_sendemail',
			type: 'boolean',
			default: false,
			description: 'Whether to send email by default',
		},
		{
			displayName: 'Default Show for Users',
			name: 'default_showforusers',
			type: 'boolean',
			default: true,
			description: 'Whether to show for users by default',
		},
		{
			displayName: 'Default SLA',
			name: 'default_sla',
			type: 'number',
			default: 0,
			description: 'Default SLA ID for tickets of this type',
		},
		{
			displayName: 'Default Summary',
			name: 'default_summary',
			type: 'string',
			default: '',
			description: 'Default summary template',
		},
		{
			displayName: 'Default Team',
			name: 'default_team',
			type: 'number',
			default: 0,
			description: 'Default team ID for tickets of this type',
		},
		{
			displayName: 'End Users Can Select',
			name: 'enduserscanselect',
			type: 'boolean',
			default: false,
			description: 'Whether end users can select this ticket type',
		},
		{
			displayName: 'Group ID',
			name: 'group_id',
			type: 'number',
			default: 0,
			description: 'ID of the ticket type group',
		},
		{
			displayName: 'Inactive',
			name: 'inactive',
			type: 'boolean',
			default: false,
			description: 'Whether the ticket type is inactive',
		},
		{
			displayName: 'Include in Mobile DB Sync',
			name: 'includeinmobiledbsync',
			type: 'boolean',
			default: false,
			description: 'Whether to include in mobile database synchronization',
		},
		{
			displayName: 'Initial Status',
			name: 'initial_status',
			type: 'number',
			default: 0,
			description: 'Initial status ID for tickets of this type',
		},
		{
			displayName: 'Intent',
			name: 'intent',
			type: 'string',
			default: '',
			description: 'Intent or purpose of the ticket type',
		},
		{
			displayName: 'ITIL Request Type',
			name: 'itilrequesttype',
			type: 'number',
			default: 0,
			description: 'ITIL request type classification',
		},
		{
			displayName: 'Name',
			name: 'name',
			type: 'string',
			default: '',
			description: 'Name of the ticket type',
		},
		{
			displayName: 'Require Manager Approval',
			name: 'require_manager_approval',
			type: 'boolean',
			default: false,
			description: 'Whether manager approval is required',
		},
		{
			displayName: 'Sequence',
			name: 'sequence',
			type: 'number',
			default: 0,
			description: 'Display sequence order',
		},
		{
			displayName: 'Survey Anonymous',
			name: 'survey_anonymous',
			type: 'boolean',
			default: false,
			description: 'Whether surveys are anonymous',
		},
		{
			displayName: 'Survey Automatically Send',
			name: 'survey_automatically_send',
			type: 'boolean',
			default: false,
			description: 'Whether to automatically send surveys',
		},
		{
			displayName: 'Survey Automatically SMS',
			name: 'survey_automatically_sms',
			type: 'boolean',
			default: false,
			description: 'Whether to automatically send SMS surveys',
		},
		{
			displayName: 'Survey Closure Mandatory',
			name: 'survey_closure_mandatory',
			type: 'boolean',
			default: false,
			description: 'Whether survey completion is mandatory for closure',
		},
		{
			displayName: 'Survey ID',
			name: 'survey_id',
			type: 'number',
			default: 0,
			description: 'Survey ID to associate with this ticket type',
		},
		{
			displayName: 'Use',
			name: 'use',
			type: 'string',
			default: '',
			description: 'Usage description of the ticket type',
		},
		{
			displayName: 'Workflow ID',
			name: 'workflow_id',
			type: 'number',
			default: 0,
			description: 'Workflow ID to associate with this ticket type',
		},
	],
	},
];