import { INodeProperties } from 'n8n-workflow';

export const description: INodeProperties[] = [
	{
		displayName: 'Ticket ID',
		name: 'ticketId',
		type: 'number',
		required: true,
		displayOptions: {
			show: {
				resource: ['actions'],
				operation: ['create'],
			},
		},
		default: 0,
		description: 'The ID of the ticket to create the action for',
	},
	{
		displayName: 'Note',
		name: 'note',
		type: 'string',
		typeOptions: {
			rows: 4,
		},
		required: true,
		displayOptions: {
			show: {
				resource: ['actions'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'The content/note for the action',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['actions'],
				operation: ['create'],
			},
		},
	options: [
			{
				displayName: 'Action Arrival Date',
				name: 'actionarrivaldate',
				type: 'dateTime',
				default: '',
				description: 'Arrival date for the action',
			},
			{
				displayName: 'Action By Agent Name or ID',
				name: 'actionby_agent_id',
				type: 'options',
				default: '',
				description: 'Agent performing the action. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
				typeOptions: {
					loadOptionsMethod: 'getAgents',
				},
				options: [],
			},
			{
				displayName: 'Action Completion Date',
				name: 'actioncompletiondate',
				type: 'dateTime',
				default: '',
				description: 'Completion date for the action',
			},
			{
				displayName: 'Action Contract ID',
				name: 'action_contract_id',
				type: 'number',
				default: 0,
				description: 'Contract ID associated with this action',
			},
			{
				displayName: 'Action Contract Ref',
				name: 'action_contract_ref',
				type: 'string',
				default: '',
				description: 'Contract reference associated with this action',
			},
			{
				displayName: 'Action Travel Contract ID',
				name: 'action_travel_contract_id',
				type: 'number',
				default: 0,
				description: 'Travel contract ID associated with this action',
			},
			{
				displayName: 'Agent Name or ID',
				name: 'who_agentid',
				type: 'options',
				default: '',
				description: 'The agent creating the action. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
				typeOptions: {
					loadOptionsMethod: 'getAgents',
				},
				options: [],
			},
			{
				displayName: 'Created From Action ID',
				name: 'created_from_action_id',
				type: 'number',
				default: 0,
				description: 'ID of the action this action was created from',
			},
			{
				displayName: 'Created From Ticket ID',
				name: 'created_from_ticket_id',
				type: 'number',
				default: 0,
				description: 'ID of the ticket this action was created from',
			},
			{
				displayName: 'Date Time',
				name: 'datetime',
				type: 'dateTime',
				default: '',
				description: 'The date and time of the action (defaults to current time if not specified)',
			},
			{
				displayName: 'Is JSON',
				name: 'isjson',
				type: 'boolean',
				default: false,
				description: 'Whether the action content is in JSON format',
			},
			{
				displayName: 'Is Pinned',
				name: 'is_pinned',
				type: 'boolean',
				default: false,
				description: 'Whether the action is pinned',
			},
			{
				displayName: 'On Behalf Of',
				name: 'on_behalf_of',
				type: 'number',
				default: 0,
				description: 'ID of the user this action is being created on behalf of',
			},
			{
				displayName: 'On Behalf Of Name',
				name: 'on_behalf_of_name',
				type: 'string',
				default: '',
				description: 'Name of the user this action is being created on behalf of',
			},
			{
				displayName: 'Outcome',
				name: 'outcome',
				type: 'string',
				default: '',
				description: 'The outcome/type of the action',
			},
			{
				displayName: 'Personal Unread',
				name: 'personal_unread',
				type: 'boolean',
				default: false,
				description: 'Whether the action is marked as unread for the user',
			},
			{
				displayName: 'Pin Order',
				name: 'pin_order',
				type: 'number',
				default: 0,
				description: 'Order of the pinned action',
			},
			{
				displayName: 'Project ID',
				name: 'project_id',
				type: 'number',
				default: 0,
				description: 'Project ID associated with this action',
			},
			{
				displayName: 'Reply To Action ID',
				name: 'replied_to_action_id',
				type: 'number',
				default: 0,
				description: 'ID of the action being replied to',
			},
			{
				displayName: 'Reply To Ticket ID',
				name: 'replied_to_ticket_id',
				type: 'number',
				default: 0,
				description: 'ID of the ticket being replied to',
			},
			{
				displayName: 'Warning Type',
				name: 'warning_type',
				type: 'number',
				default: 0,
				description: 'Warning type associated with the action',
			},
			{
				displayName: 'Who Type',
				name: 'who_type',
				type: 'number',
				default: 0,
				description: 'The type of user creating the action',
			},
		],
	},
];