import { INodeProperties } from 'n8n-workflow';

export const getAllDescription: INodeProperties[] = [
	{ displayName: 'Return All', name: 'returnAll', type: 'boolean',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } },
		default: false, description: 'Whether to return all results or only up to a given limit' },
	{ displayName: 'Limit', name: 'limit', type: 'number',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'], returnAll: [false] } },
		typeOptions: { minValue: 1 }, default: 50, description: 'Max number of results to return' },
	{ displayName: 'Client ID', name: 'clientId', type: 'number',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: 0,
		description: 'Maps to related_client_id' },
	{ displayName: 'Site ID', name: 'siteId', type: 'number',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: 0 },
	{ displayName: 'User ID', name: 'userId', type: 'number',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: 0 },
	{ displayName: 'Ticket ID', name: 'ticketId', type: 'number',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: 0,
		description: 'Maps to one_agents_tickets_id' },
	{ displayName: 'Asset ID', name: 'assetId', type: 'number',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: 0 },
	{ displayName: 'Agent Only', name: 'agentOnly', type: 'boolean',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: false },
	{ displayName: 'Followed Only', name: 'followedOnly', type: 'boolean',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: false },
	{ displayName: 'Exclude Private', name: 'excludePrivate', type: 'boolean',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: false },
	{ displayName: 'Count', name: 'count', type: 'number',
		displayOptions: { show: { resource: ['feed'], operation: ['getAll'] } }, default: 0,
		description: 'API count parameter (0 = omit)' },
];
