import { INodeProperties } from 'n8n-workflow';

export const agentInlineRouting: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['agents'],
			},
		},
	options: [
		{
			name: 'Create',
			value: 'create',
			description: 'Create a new agent',
			action: 'Create an agent',
			routing: {
				request: {
					method: 'POST',
					url: '/Agent',
					body: {
						name: '={{ $parameter.name }}',
						emailaddress: '={{ $parameter.emailaddress }}',
						surname: '={{ $parameter.additionalFields?.surname || undefined }}',
						inactive: '={{ $parameter.additionalFields?.inactive || undefined }}',
						department_id: '={{ $parameter.additionalFields?.department_id || undefined }}',
						team_ids: '={{ $parameter.additionalFields?.team_ids || undefined }}',
						phonenumber: '={{ $parameter.additionalFields?.phonenumber || undefined }}',
						mobilenumber: '={{ $parameter.additionalFields?.mobilenumber || undefined }}',
						isserviceaccount: '={{ $parameter.additionalFields?.isserviceaccount || undefined }}',
						isimportantcontact: '={{ $parameter.additionalFields?.isimportantcontact || undefined }}',
						colour: '={{ $parameter.additionalFields?.colour || undefined }}',
						startdate: '={{ $parameter.additionalFields?.startdate || undefined }}',
						jobname: '={{ $parameter.additionalFields?.jobname || undefined }}',
						notes: '={{ $parameter.additionalFields?.notes || undefined }}',
					},
				},
			},
		},
		{
			name: 'Delete',
			value: 'delete',
			description: 'Delete an agent',
			action: 'Delete an agent',
			routing: {
				request: {
					method: 'DELETE',
					url: '=/Agent/{{ $parameter.agentId }}',
				},
				output: {
					postReceive: [
						{
							type: 'set',
							properties: {
								value: '={{ { "success": true, "id": $parameter.agentId } }}',
							},
						},
					],
				},
			},
		},
		{
			name: 'Get by ID',
			value: 'getById',
			description: 'Get an agent by ID',
			action: 'Get an agent by ID',
			routing: {
				request: {
					method: 'GET',
					url: '=/Agent/{{ $parameter.agentId }}',
					qs: {
						includedetails: '={{ $parameter.options?.includedetails || undefined }}',
						includehiddenfields: '={{ $parameter.options?.includehiddenfields || undefined }}',
						includeroles: '={{ $parameter.options?.includeroles || undefined }}',
						includestatus: '={{ $parameter.options?.includestatus || undefined }}',
					},
				},
			},
		},
		{
			name: 'Get Many',
			value: 'getAll',
			description: 'Get many agents',
			action: 'Get many agents',
			routing: {
				request: {
					method: 'GET',
					url: '/Agent',
					qs: {
						count: '={{ !$parameter.returnAll ? ($parameter.limit || 50) : undefined }}',
						activeinactive: '={{ $parameter.filters?.activeinactive || undefined }}',
						appointmentscreen: '={{ $parameter.filters?.appointmentscreen || undefined }}',
						basic_fields_only: '={{ $parameter.filters?.basic_fields_only || undefined }}',
						can_edit_only: '={{ $parameter.filters?.can_edit_only || undefined }}',
						client_id: '={{ $parameter.filters?.client_id || undefined }}',
						clientidoverride: '={{ $parameter.filters?.clientidoverride || undefined }}',
						department_id: '={{ $parameter.filters?.department_id || undefined }}',
						departments: '={{ $parameter.filters?.departments || undefined }}',
						domain: '={{ $parameter.filters?.domain || undefined }}',
						exchangecalendars: '={{ $parameter.filters?.exchangecalendars || undefined }}',
						exclude_membership_info: '={{ $parameter.filters?.exclude_membership_info || undefined }}',
						excludeAgent: '={{ $parameter.filters?.excludeAgent || undefined }}',
						forcequalmatch: '={{ $parameter.filters?.forcequalmatch || undefined }}',
						include_membership_info: '={{ $parameter.filters?.include_membership_info || undefined }}',
						includeapiagents: '={{ $parameter.filters?.includeapiagents || undefined }}',
						includedisabled: '={{ $parameter.filters?.includedisabled || undefined }}',
						includeenabled: '={{ $parameter.filters?.includeenabled || undefined }}',
						includenamedcount: '={{ $parameter.filters?.includenamedcount || undefined }}',
						includeroles: '={{ $parameter.filters?.includeroles || undefined }}',
						includestatus: '={{ $parameter.filters?.includestatus || undefined }}',
						includeunassigned: '={{ $parameter.filters?.includeunassigned || undefined }}',
						is_agent_cache: '={{ $parameter.filters?.is_agent_cache || undefined }}',
						integration_type: '={{ $parameter.filters?.integration_type || undefined }}',
						linemanagedonly: '={{ $parameter.filters?.linemanagedonly || undefined }}',
						linkingagents: '={{ $parameter.filters?.linkingagents || undefined }}',
						loadcache: '={{ $parameter.filters?.loadcache || undefined }}',
						onlinestatuses: '={{ $parameter.filters?.onlinestatuses || undefined }}',
						order: '={{ $parameter.filters?.order || undefined }}',
						order2: '={{ $parameter.filters?.order2 || undefined }}',
						order3: '={{ $parameter.filters?.order3 || undefined }}',
						order4: '={{ $parameter.filters?.order4 || undefined }}',
						order5: '={{ $parameter.filters?.order5 || undefined }}',
						orderdesc: '={{ $parameter.filters?.orderdesc || undefined }}',
						orderdesc2: '={{ $parameter.filters?.orderdesc2 || undefined }}',
						orderdesc3: '={{ $parameter.filters?.orderdesc3 || undefined }}',
						orderdesc4: '={{ $parameter.filters?.orderdesc4 || undefined }}',
						orderdesc5: '={{ $parameter.filters?.orderdesc5 || undefined }}',
						page_no: '={{ $parameter.filters?.page_no || undefined }}',
						page_size: '={{ $parameter.filters?.page_size || undefined }}',
						pageinate: '={{ $parameter.filters?.pageinate || undefined }}',
						qualifications: '={{ $parameter.filters?.qualifications || undefined }}',
						reassign: '={{ $parameter.filters?.reassign || undefined }}',
						remoteagents: '={{ $parameter.filters?.remoteagents || undefined }}',
						remoteagenttype: '={{ $parameter.filters?.remoteagenttype || undefined }}',
						role: '={{ $parameter.filters?.role || undefined }}',
						search: '={{ $parameter.filters?.search || undefined }}',
						shiftagentsonly: '={{ $parameter.filters?.shiftagentsonly || undefined }}',
						showall: '={{ $parameter.filters?.showall || undefined }}',
						showcounts: '={{ $parameter.filters?.showcounts || undefined }}',
						team: '={{ $parameter.filters?.team || undefined }}',
						team_id: '={{ $parameter.filters?.team_id || undefined }}',
						teams: '={{ $parameter.filters?.teams || undefined }}',
						thisAgentOnly: '={{ $parameter.filters?.thisAgentOnly || undefined }}',
						ticketarea_id: '={{ $parameter.filters?.ticketarea_id || undefined }}',
						tickettype_id: '={{ $parameter.filters?.tickettype_id || undefined }}',
						view_id: '={{ $parameter.filters?.view_id || undefined }}',
						withemail: '={{ $parameter.filters?.withemail || undefined }}',
					},
				},
				output: {
					postReceive: [
						{
							type: 'rootProperty',
							properties: {
								property: 'agents',
							},
						},
					],
				},
			},
		},
		{
			name: 'Update',
			value: 'update',
			description: 'Update an agent',
			action: 'Update an agent',
			routing: {
				request: {
					method: 'POST',
					url: '/Agent',
					body: {
						id: '={{ $parameter.agentId }}',
						name: '={{ $parameter.updateFields?.name || undefined }}',
						surname: '={{ $parameter.updateFields?.surname || undefined }}',
						emailaddress: '={{ $parameter.updateFields?.emailaddress || undefined }}',
						inactive: '={{ $parameter.updateFields?.inactive || undefined }}',
						department_id: '={{ $parameter.updateFields?.department_id || undefined }}',
						team_ids: '={{ $parameter.updateFields?.team_ids || undefined }}',
						phonenumber: '={{ $parameter.updateFields?.phonenumber || undefined }}',
						mobilenumber: '={{ $parameter.updateFields?.mobilenumber || undefined }}',
						isserviceaccount: '={{ $parameter.updateFields?.isserviceaccount || undefined }}',
						isimportantcontact: '={{ $parameter.updateFields?.isimportantcontact || undefined }}',
						colour: '={{ $parameter.updateFields?.colour || undefined }}',
						startdate: '={{ $parameter.updateFields?.startdate || undefined }}',
						jobname: '={{ $parameter.updateFields?.jobname || undefined }}',
						notes: '={{ $parameter.updateFields?.notes || undefined }}',
					},
				},
			},
		},
		],
		default: 'getAll',
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getAll'],
			},
		},
	options: [
		{
			displayName: 'Department ID',
			name: 'department_id',
			type: 'number',
			default: 0,
			description: 'Filter agents belonging to a particular department',
		},
		{
			displayName: 'Include Roles',
			name: 'includeroles',
			type: 'boolean',
			default: false,
			description: 'Whether to include agent roles in the response',
		},
		{
			displayName: 'Include Status',
			name: 'includestatus',
			type: 'boolean',
			default: false,
			description: 'Whether to include agent status in the response',
		},
		{
			displayName: 'Search',
			name: 'search',
			type: 'string',
			default: '',
			description: 'Filter by agents with a name, email address or telephone number like your search',
		},
		{
			displayName: 'Team ID',
			name: 'team_id',
			type: 'number',
			default: 0,
			description: 'Filter by agents within a particular team ID',
		},
		],
	},
	{
		displayName: 'Agent ID',
		name: 'agentId',
		type: 'number',
		required: true,
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getById', 'update', 'delete'],
			},
		},
		default: 0,
		description: 'The ID of the agent',
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'The name of the agent',
	},
	{
		displayName: 'Email Address',
		name: 'emailaddress',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'The email address of the agent',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['create'],
			},
		},
	options: [
		{
			displayName: 'Department ID',
			name: 'department_id',
			type: 'number',
			default: 0,
			description: 'The department ID of the agent',
		},
		{
			displayName: 'Inactive',
			name: 'inactive',
			type: 'boolean',
			default: false,
			description: 'Whether the agent is inactive',
		},
		{
			displayName: 'Phone Number',
			name: 'phonenumber',
			type: 'string',
			default: '',
			description: 'The phone number of the agent',
		},
		{
			displayName: 'Surname',
			name: 'surname',
			type: 'string',
			default: '',
			description: 'The surname of the agent',
		},
	],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['update'],
			},
		},
	options: [
		{
			displayName: 'Department ID',
			name: 'department_id',
			type: 'number',
			default: 0,
			description: 'The department ID of the agent',
		},
		{
			displayName: 'Email Address',
			name: 'emailaddress',
			type: 'string',
			default: '',
			description: 'The email address of the agent',
		},
		{
			displayName: 'Inactive',
			name: 'inactive',
			type: 'boolean',
			default: false,
			description: 'Whether the agent is inactive',
		},
		{
			displayName: 'Name',
			name: 'name',
			type: 'string',
			default: '',
			description: 'The name of the agent',
		},
		{
			displayName: 'Phone Number',
			name: 'phonenumber',
			type: 'string',
			default: '',
			description: 'The phone number of the agent',
		},
		{
			displayName: 'Surname',
			name: 'surname',
			type: 'string',
			default: '',
			description: 'The surname of the agent',
		},
	],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['agents'],
				operation: ['getById'],
			},
		},
		options: [
			{
				displayName: 'Include Details',
				name: 'includedetails',
				type: 'boolean',
				default: false,
				description: 'Whether to include additional details',
			},
			{
				displayName: 'Include Roles',
				name: 'includeroles',
				type: 'boolean',
				default: false,
				description: 'Whether to include agent roles',
			},
			{
				displayName: 'Include Status',
				name: 'includestatus',
				type: 'boolean',
				default: false,
				description: 'Whether to include agent status',
			},
		],
	},
];