import { INodeProperties } from 'n8n-workflow';

export const getALLDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['fieldInfo'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['fieldInfo'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['fieldInfo'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Access Control Level',
				name: 'access_control_level',
				type: 'number',
				default: 0,
				description: 'Filter by access control level',
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: '',
				description: 'Domain filter',
			},
			{
				displayName: 'Exclude Ranges',
				name: 'excluderanges',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude ranges',
			},
			{
				displayName: 'Exclude Table Self',
				name: 'excludetableself',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude table self references',
			},
			{
				displayName: 'Exclude Tables',
				name: 'excludetables',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude tables',
			},
			{
				displayName: 'Extra Type',
				name: 'extratype',
				type: 'number',
				default: 0,
				description: 'Filter by extra type',
			},
			{
				displayName: 'Field Type',
				name: 'fieldtype',
				type: 'number',
				default: 0,
				description: 'Filter by field type',
			},
			{
				displayName: 'Field Type Multiple',
				name: 'fieldtypemultiple',
				type: 'string',
				default: '',
				description: 'Comma-separated list of field types to filter by',
			},
			{
				displayName: 'Include Categories',
				name: 'includecategories',
				type: 'boolean',
				default: false,
				description: 'Whether to include categories',
			},
			{
				displayName: 'Include Date Fields',
				name: 'includedatefields',
				type: 'boolean',
				default: false,
				description: 'Whether to include date fields',
			},
			{
				displayName: 'Include Jira Fields',
				name: 'includejirafields',
				type: 'boolean',
				default: false,
				description: 'Whether to include Jira fields',
			},
			{
				displayName: 'Include Remote Fields',
				name: 'includeremotefields',
				type: 'boolean',
				default: false,
				description: 'Whether to include remote fields',
			},
			{
				displayName: 'Include Values',
				name: 'includevalues',
				type: 'boolean',
				default: false,
				description: 'Whether to include field values',
			},
			{
				displayName: 'Input Type',
				name: 'inputtype',
				type: 'number',
				default: 0,
				description: 'Filter by input type',
			},
			{
				displayName: 'Is Approval Step',
				name: 'isapprovalstep',
				type: 'boolean',
				default: false,
				description: 'Whether this is an approval step field',
			},
			{
				displayName: 'Is Config',
				name: 'isconfig',
				type: 'boolean',
				default: false,
				description: 'Whether this is a configuration field',
			},
			{
				displayName: 'Is Custom Field Setup',
				name: 'iscustomfieldsetup',
				type: 'boolean',
				default: false,
				description: 'Whether this is a custom field setup',
			},
			{
				displayName: 'System ID',
				name: 'systemid',
				type: 'number',
				default: 0,
				description: 'Filter by system ID',
			},
			{
				displayName: 'Type ID',
				name: 'typeid',
				type: 'number',
				default: 0,
				description: 'Filter by type ID (2 = Client custom fields)',
			},
		],
	},
];