import { INodeProperties } from 'n8n-workflow';

export const getALLDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['invoices'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['invoices'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['invoices'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Advanced Search',
				name: 'advanced_search',
				type: 'string',
				default: '',
				description: 'Advanced search string',
			},
			{
				displayName: 'Asset ID',
				name: 'asset_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified asset',
			},
			{
				displayName: 'Awaiting Approval',
				name: 'awaiting_approval',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on awaiting approval',
			},
			{
				displayName: 'Billing Date',
				name: 'billing_date',
				type: 'dateTime',
				default: '',
				description: 'Filter on billing date',
			},
			{
				displayName: 'Client ID',
				name: 'client_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified client',
			},
			{
				displayName: 'Contract ID',
				name: 'contract_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified contract',
			},
			{
				displayName: 'Currency Code',
				name: 'currency_code',
				type: 'string',
				default: '',
				description: 'Filter by currency code',
			},
			{
				displayName: 'Date Search Field',
				name: 'datesearch',
				type: 'options',
				options: [
					{
						name: '-- Select Date Field --',
						value: '',
						description: 'Choose a date field to filter by (required when using Start/End Date)',
					},
					{
						name: 'Billing Date',
						value: 'billing_date',
						description: 'Date when the invoice was billed',
					},
					{
						name: 'Due Date',
						value: 'due_date',
						description: 'Date when payment is due',
					},
					{
						name: 'Invoice Date',
						value: 'invoice_date',
						description: 'Date when the invoice was created',
					},
					{
						name: 'Posted Date',
						value: 'posted_date',
						description: 'Date when the invoice was posted',
					},
					{
						name: 'Schedule Date',
						value: 'schedule_date',
						description: 'Scheduled date for the invoice',
					},
				],
				default: '',
				description: 'REQUIRED when using Start Date or End Date - Select which date field to search against',
			},
			{
				displayName: 'End Date',
				name: 'enddate',
				type: 'dateTime',
				default: '',
				description: 'For use with the datesearch parameter',
			},
			{
				displayName: 'Exclude Voided',
				name: 'exclude_voided',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude voided invoices',
			},
			{
				displayName: 'Include Details',
				name: 'includedetails',
				type: 'boolean',
				default: false,
				description: 'Whether to include extra objects in the response',
			},
			{
				displayName: 'Include Linked Item Details',
				name: 'include_linked_item_details',
				type: 'boolean',
				default: false,
				description: 'Whether to include invoice lines linked item details',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'string',
				default: '',
				description: 'The name of the field to order by first',
			},
			{
				displayName: 'Order 2',
				name: 'order2',
				type: 'string',
				default: '',
				description: 'The name of the field to order by second',
			},
			{
				displayName: 'Order 3',
				name: 'order3',
				type: 'string',
				default: '',
				description: 'The name of the field to order by third',
			},
			{
				displayName: 'Order 4',
				name: 'order4',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fourth',
			},
			{
				displayName: 'Order 5',
				name: 'order5',
				type: 'string',
				default: '',
				description: 'The name of the field to order by fifth',
			},
			{
				displayName: 'Order Desc',
				name: 'orderdesc',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on first order',
			},
			{
				displayName: 'Order Desc 2',
				name: 'orderdesc2',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on second order',
			},
			{
				displayName: 'Order Desc 3',
				name: 'orderdesc3',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on third order',
			},
			{
				displayName: 'Order Desc 4',
				name: 'orderdesc4',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fourth order',
			},
			{
				displayName: 'Order Desc 5',
				name: 'orderdesc5',
				type: 'boolean',
				default: false,
				description: 'Whether to order ascending or descending on fifth order',
			},
			{
				displayName: 'Page Number',
				name: 'page_no',
				type: 'number',
				default: 0,
				description: 'When using pagination, the page number to return',
			},
			{
				displayName: 'Page Size',
				name: 'page_size',
				type: 'number',
				default: 0,
				typeOptions: {
					maxValue: 100,
				},
				description: 'When using pagination, the size of the page (max: 100)',
			},
			{
				displayName: 'Paginate',
				name: 'pageinate',
				type: 'boolean',
				default: false,
				description: 'Whether to use pagination in the response',
			},
			{
				displayName: 'Payment Statuses',
				name: 'paymentstatuses',
				type: 'string',
				default: '',
				description: 'Filter on invoice payment status, comma-separated int',
			},
			{
				displayName: 'Posted Only',
				name: 'postedonly',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on invoices that have been posted',
			},
			{
				displayName: 'Purchase Order ID',
				name: 'purchaseorder_id',
				type: 'number',
				default: 0,
				description: 'Filter by purchase order ID',
			},
			{
				displayName: 'QuickBooks ID',
				name: 'quickbooks_id',
				type: 'number',
				default: 0,
				description: 'Find an invoice using QuickBooks Online ID',
			},
			{
				displayName: 'Quote Status',
				name: 'quote_status',
				type: 'string',
				default: '',
				description: 'Filter by the specified quote statuses, comma-separated',
			},
			{
				displayName: 'R Invoice Type',
				name: 'rinvoice_type',
				type: 'options',
				options: [
					{
						name: 'Contracts',
						value: 'contracts',
						description: 'Filter on contracts',
					},
					{
						name: 'Invoices',
						value: 'invoices',
						description: 'Filter on invoices',
					},
					{
						name: 'Both',
						value: 'both',
						description: 'Filter on both contracts and invoices',
					},
				],
				default: 'contracts',
				description: 'Filter on invoice type',
			},
			{
				displayName: 'Ready for Invoicing',
				name: 'ready_for_invoicing',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on whether the invoice is ready for invoicing',
			},
			{
				displayName: 'Recurring Invoice ID',
				name: 'recurringinvoice_id',
				type: 'number',
				default: 0,
				description: 'Filter by contracts recurring invoice ID',
			},
			{
				displayName: 'Review Required',
				name: 'reviewrequired',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on review required',
			},
			{
				displayName: 'Sales Order ID',
				name: 'salesorder_id',
				type: 'number',
				default: 0,
				description: 'Filter by contracts sales order ID',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filter response based on the search string',
			},
			{
				displayName: 'Sent Status',
				name: 'sent_status',
				type: 'number',
				default: 0,
				description: 'Filter by sent status',
			},
			{
				displayName: 'Site ID',
				name: 'site_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified site',
			},
			{
				displayName: 'Start Date',
				name: 'startdate',
				type: 'dateTime',
				default: '',
				description: 'For use with the datesearch parameter',
			},
			{
				displayName: 'Stripe Auto Payment Required',
				name: 'stripeautopaymentrequired',
				type: 'boolean',
				default: false,
				description: 'Whether to filter on Stripe auto payment required',
			},
			{
				displayName: 'Third Party ID',
				name: 'third_party_id',
				type: 'string',
				default: '',
				description: 'Find an invoice using Third Party Invoice Number',
			},
			{
				displayName: 'Ticket ID',
				name: 'ticket_id',
				type: 'number',
				default: 0,
				description: 'Return contracts assigned to a particular ticket',
			},
			{
				displayName: 'Top Level ID',
				name: 'toplevel_id',
				type: 'number',
				default: 0,
				description: 'Filter by top level ID',
			},
			{
				displayName: 'User ID',
				name: 'user_id',
				type: 'number',
				default: 0,
				description: 'Filter by the specified user',
			},
			{
				displayName: 'Xero ID',
				name: 'xero_id',
				type: 'string',
				default: '',
				description: 'Find an invoice using Xero Online ID',
			},
		],
	},
];